### ISSUE TITLE
document using a dotplot to evaluate alignment quality

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1063]
**Describe the solution you'd like**
The dotplot algorithm can show both matching segments between sequences AND the path an alignment algorithm has chosen.

Write a gallery document that shows this feature, explaining how it's useful.

The document should demonstrate using an aligner with bad parameter values. Apply it to the brca1.fasta file. Embellish the following with explanatory text of alignment parameters, what a dotplot shows, how to modify the dotplot display, etc...
```python
from cogent3 import load_aligned_seqs
from cogent3.app.align import progressive_align

seqs = load_aligned_seqs("/Users/gavin/repos/Cogent3/doc/data/brca1.fasta", moltype="dna").degap()
seqs = seqs.take_seqs(['LeafNose',
 'FalseVamp',
 'RoundEare',
 'Sloth',
 'Anteater',
 'HairyArma'])

# bad idea! make gap extension unlikely
aligner = progressive_align("nucleotide", indel_length=1e-9, indel_rate=1e-2)
aln = aligner(seqs)
aln[2200:2500].dotplot("HairyArma", "RoundEare").show()
aln[2270:2500] # showing poorly aligned segment

# run with aligner defaults
aligner = progressive_align("nucleotide")
aln = aligner(seqs)
aln[2200:2500].dotplot("HairyArma", "RoundEare").show()
aln[2270:2500] # showing poorly aligned segment
```

**Comment by KatherineCaley** [comment]
I'll work on this! ✋
