### ISSUE TITLE
define default wrapped function for Composable

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1075]
### Discussed in https://github.com/cogent3/cogent3/discussions/1071

Currently, the default function name is `func`, defined in the constructor. This should be renamed to `main()` and defined in the base Composable class as an abstract base class.

**Comment by Nick-Foto** [comment]
@GavinHuttley
I think this is a suitable issue to start refactoring Composable Class. If you agree I work on this.

**Comment by GavinHuttley** [comment]
@Nick-Foto Awesome!

Note I have pushed some patches that progress towards this. Specifically all current apps now have a `<app>.main()` method. This means there should be less work in getting the abstract base class implemented with the abstract main method on it.

What's not made explicit by the above issue definition is that there are two classes `Composable` which inherits from `ComposableType`. I think they should be merged into a single abstract class. What should that class be called: `Composable`, `ComposableABC`? or `ComposableBase` or? What is the convention in the Python community. Perhaps do a quick google and also search GitHub for major Python projects like `attrs` or `pytest` and see if they use abstract classes (`@abstractmethod` might work as a way to identify code implementing ABC's).

**Comment by GavinHuttley** [comment]
Thanks. I think we should go with `ComposableBase`.

**Comment by GavinHuttley** [comment]
Fixed in cd6f5ea359570851dc2b4dc0a5dd98f64420f948
