### ISSUE TITLE
All composable app subclasses should inherit from Composable

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1083]
In `cogent3.app.composable`, from lines 514-557, I define subclasses of `Composable`, e.g. `ComposableHypothesis`. These are not being used in any meaningful way.

Change all classes that inherit from these subclasses to inherit instead from the parent `Composable` class instead. 

Within each constructor add a `cogent3.util.warnings.discontinued` warning, indicating these classes will be deleted in version "2023.1". Here's an example of how to use that warning.
```python
class ComposableDistance(Composable):
    _type = "distance"

    def __init__(self, **kwargs):
        super(ComposableDistance, self).__init__(**kwargs)
        discontinued("class", "ComposableDistance", "2023.1", "see developer docs for new class hierarchy")
```

**Comment by Nick-Foto** [comment]
@GavinHuttley 
In the above comment, you mentioned those are subclasses of `Composable`, and then "Change all classes that inherit from these to inherit instead from Composable". I think there is a missed name.

**Comment by GavinHuttley** [comment]
Have updated statement, is that clearer?

**Comment by Nick-Foto** [comment]
@GavinHuttley 
Yes, Thank you.

**Comment by Nick-Foto** [comment]
@GavinHuttley   
Fixed in 195a65dd041b66b50f44c3ee2802bf737ee20bce

**Comment by Nick-Foto** [comment]
@GavinHuttley   
You didn't close this ticket. Is there any task remained?

**Comment by GavinHuttley** [comment]
Missed it, sorry. Thanks for the patch!
