### ISSUE TITLE
Create single Composable abstract base class

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1084]
Best done after #1083

Merge `ComposableType` and `Composable` methods into a single new class `ComposableBase`.

Denote `def main()`  as an `abstractmethod`.

**Comment by Nick-Foto** [comment]
@GavinHuttley 
I am thinking if it will be better to use Protocol architecture instead of inheriting a class from abc.ABC .
Now, I am reading texts about this. Protocol started from Python 3.8 .

**Comment by Nick-Foto** [comment]
@GavinHuttley 
If we use Protocol, we don't have to use inheritance. Users need to implement some functions (as class methods) with a specific signature. This prevents using multiple inheritance and decreases coupling between classes.

**Comment by GavinHuttley** [comment]
@Nick-Foto Let's expand the use case and consider how it would be solved using an ABC.

The overall objective is make it easy for a developer to write their own composable app. The objective with an abstract base class is to define both an interface **and** *implement concrete* methods. The latter define the essence of Composability.

```python
class ComposableBase(abc.ABC):
  """base class for apps which can be combined with others
  and do not fail when called, returning NotCompleted instead"""
  
  @abstractmethod
  def main(self, data, **args, **kwargs):
    """data must be type-hinted since this is used to identify composable functions that provide compatible input
    the return value of main() must be type hinted since this is used to establish whether this is compatbile as input"""
  
  def __add__(self, other: "Composable"):
    # this is a concrete method that - at runtime - is
    # responsible for the composability of instances
    # it does this by identifying whether the return type this instances self.main
    # is consistent with the type of the data parameter of other.main()
 	
  def __call__(self, data, *args, **kwargs):
    # a concrete method that intercepts execution of the instances
    # main(). At present this is done by passing it through _trapped_call
  
  def _trapped_call(self, data, *args, **kwargs):
    # this is a concrete method that - at runtime - validates
    # data matches the type declared on main(data:), returning
    # an informative NotCompleted instance if condition is not
    # satisfied.
    # It then executes main()
```

To use this a developer does the following:

1. Inherits from `ComposableBase`, providing their own constructor. (**Protocols can do this.**)

2. **Must** define `main()` otherwise their code fails. (**Protocols can do this.**)

3. **Must** define type hints on `main()` otherwise their code fails *at the composability step* but otherwise executes, trapping any exceptions that occur  (**Protocols cannot do this!**)

What the developer gets is that by just writing type hints they define how their app can be used in concert with other apps. They also get the error trapping.

I've indicated in bold where I think Protocols work and don't work. For point (3), it would be possible to provide functions that developers could use that provide these capabilities, but I think they are unnecessarily complex.

There are 3 cases of multiple inheritance within `cogent3` apps (all within `cogent3.app.io`. They can each be reduced to single inheritance trivially. Not one actually requires multiple inheritance, e.g. `write_tabular` should only inherit from `ComposableBase` and the mixin class `_seq_loader` has one method only. So that can be replaced with a single function call!

There's nothing to stop other developers from using multiple-inheritance with the above ABC. Likewise, there's nothing to stop other developers from using multiple-inheritance even if we provided Protocols!

It maybe that my understanding of Protocol's is incomplete, in which case I'm happy to be corrected. Otherwise, we will do the ABC.

**Comment by GavinHuttley** [comment]
Here's a remark on the [PEP 544 describing Protocols](https://peps.python.org/pep-0544/)

> Python abstract base classes [abstract-classes] are the standard library tool to provide some functionality similar to structural subtyping. The drawback of this approach is the necessity to either subclass the abstract class or register an implementation explicitly...
> As mentioned in the rationale, we want to avoid such necessity, especially in static context. **However, in a runtime context, ABCs are good candidates for protocol classes** and they are already used extensively in the typing module

**Comment by Nick-Foto** [comment]
@GavinHuttley 
Thank you for complete explanation.
I am also thinking it maybe a good idea to use `__slots__` in the base class `ComposableBase` and other classes to create a constraint on class members, preventing dynamically creating new members, saving memory and increasing memory access speed.

**Comment by GavinHuttley** [comment]
@Nick-Foto This is an important consideration and I will note here that several data containing classes will benefit from using slots. But apps do not contain data and so, with respect to `ComposableBase`, I disagree. I will create separate issues related to the core data types when it becomes necessary to address them.

Apps require custom attributes on a per-app basis. Compare the app attributes of `sample.take_codon_positions` and `sample.take_named_seqs`. As there's virtually nothing in common I don't see how you could define slots (perhaps something I don't understand about slots in abstract base classes??) in the base class. So definitely no `__slots__` in `ComposableBase`.

This would not stop a developer from using slots in their own apps. 

I note here that:
- I have never seen more than ~10 apps in a program and thus I claim app memory is unlikely to be an issue
-  most compute intensive parts of the `cogent3` code-base use `numpy+numba`, so compute efficiency is delivered through those libraries.
- there are data classes whose memory and compute performance requires refactoring, but that will be addressed as separate issues

**Comment by GavinHuttley** [comment]
We resolved this by using a decorator approach (see 418e172897807f0b3b09560656d74712907657ee)
