### ISSUE TITLE
tests need to be updated to reflect removal of Composable._type

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1088]
I shouldn't have merged the previous PR!

If you run the tests you'll note that there are tests of the repr() of composable apps. Those tests will need to be updated to reflect the removal of `type="blah"`.

**Comment by Nick-Foto** [comment]
@GavinHuttley
Please close this issue.
Fixed in e5ad2403c7316b356551a8e7c3f18466bc8db7fc
