### ISSUE TITLE
Remove multiple inheritance from cogent3.app.io classes

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1089]
The attached patch can be applied as
```
$ unzip path/to/refactor_app_io.patch.zip
$ patch -p1 < path/to/refactor_app_io.patch
```
Tests should all pass
[refactor_app_io.patch.zip](https://github.com/cogent3/cogent3/files/9075973/refactor_app_io.patch.zip)

**Comment by Nick-Foto** [comment]
Fixed in 51aa602c53d50f0b0aa52d96459c92f599407d0f
