### ISSUE TITLE
remove unused mixin class

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1098]
`composable._seq_loader` is no longer being used and should be deleted.

**Comment by Nick-Foto** [comment]
@GavinHuttley 
This issue fixed and text "Fixed #1098" was in the commit title, but it is not closed automatically.

**Comment by GavinHuttley** [comment]
@Nick-Foto  Well that's annoying! In the next case, try `<main commit message>, fixed #<isssue num>`
