### ISSUE TITLE
DEV: pin versions of black and isort

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1156]
This is essential for the new developer experience -- avoiding situation where they run the linters and generate massive numbers of changes.

**Comment by khiron** [comment]
I have a procedure ready for adding specific versions of Black/Isort to a local repository pre-commit hooks which I am using locally, and a github action for the repo.  

The cost involved is an additional noticeable delay added to every local commit, and a delay on the order of 15 mins added to checking in by the a github action.

I haven't implemented the github actions globally until we could give developers a head's up about the change in expected commit time.

**Comment by GavinHuttley** [comment]
closed ages ago
