### ISSUE TITLE
refactor cogent3.parse.genbank.Location to be PEP8 compliant

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1193]
The constructor arguments should all be deprecated in favour of pep8 compliant versions. The general approach needs to be
```python
class Location:
    def __init__(
        self,
        data,
        Ambiguity=None,
        ... # all the other args
       **kwargs
      ):
      # loop over key/value items of kwargs and assign key to corresponding pep8 compliant arg
      # collect deprecation messages
       # if any messages, call deprecated() with a date 6 months from the day you write the code
```
As this is a deprecated function/argument, see [dev guidelines for deprecation](https://github.com/cogent3/c3dev/wiki/Deprecating-Code) of code. Indicate the limiting version (for when the old function/argument will be removed) as 6 months from when you make the change.

**Comment by GavinHuttley** [comment]
This needs to be done before any publication.

**Comment by Nick-Foto** [comment]
@GavinHuttley 
I will be happy to do this.
