### ISSUE TITLE
DEV: explore different code coverage tools

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1196]
getting too many CI failures due to codecov.

We need a tool that supports GitHub actions.

One suggestion is https://coveralls.io

Another is outlined by [Hynek](https://hynek.me/articles/ditch-codecov-python/)

**Comment by Nick-Foto** [comment]
@GavinHuttley  
Did you try this option:
fail_ci_if_error: false

**Comment by Nick-Foto** [comment]
@GavinHuttley   
Did you see this page:
https://github.com/codecov/codecov-action/issues/598

**Comment by GavinHuttley** [comment]
> @GavinHuttley  
> 
> Did you try this option:
> 
> fail_ci_if_error: false

That doesn't solve issue since I rely on the codecov report as part of PR evaluation.

**Comment by GavinHuttley** [comment]
> @GavinHuttley   
> 
> Did you see this page:
> 
> https://github.com/codecov/codecov-action/issues/598

There are **too many** such issues. None of the ones I've seen explain why our uploads work sometimes, but not all the time.

My conclusion is we need to replace codecov. The replacement is not obvious to me.

**Comment by GavinHuttley** [comment]
I have coveralls working for SciTrack. See [the workflow file there](https://github.com/HuttleyLab/scitrack/blob/develop/.github/workflows/testing_develop.yml). You will also need to modify the `noxfile.py` so that it matches the cov output format and path setting as per the [scitrack version](https://github.com/HuttleyLab/scitrack/blob/develop/noxfile.py).
