### ISSUE TITLE
add Lin-Rajan-Moret tree distance metric

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1209]
I had intended to work with Yu Lin on adding this, but now as he has tragically passed away I think it's even more imperative.

The measure, which Yu Lin called the "matching distance" is superior to the Robinson-Foulds measure. The implementation should use [scipy for the assignment problem component](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html) since we already have scipy as a dependency.

## Proposed API

Adhere to PEP8 names ( see [cogent3 coding style](https://github.com/cogent3/c3dev/wiki/Coding-Style)).

Add a new `cogent3/phylo/tree_distance.py` module.

In that new module, add a function `lin_rajan_moret(tree1: PhyloNode, tree2: PhyloNode): -> float`. Conversion of the trees to the matrices required should be done in separate function(s) within the module that are called within `lin_rajan_moret()`. Those other functions should be semi-private (use a leading underscore, e.g. `_tree_to_matrix()`).

## Proposed docstring

In addition to following the numpydoc style, should include the citation of Yu Lin's paper under the `Notes` section.

## Proposed tests

Use pytest.

Add a `tests/test_tree_distance.py` module (the tests need to be re-organised, so this location will be changed later).

The `lin_rajan_moret()` function should raise a `ValueError` if the trees do not have matching tip sets (use `set(<tree>.get_tip_names())` for the comparison) OR if they are rooted trees (i.e. `len(<tree base>.children) == 2`). Tests should check these conditions raise the `ValueError`.

The `lin_rajan_moret()` should return the expected distance of 0 for identical shapes (but different orientations), e.g. the distance between `(a, b, (c, d))` and `(c, d, (a, b))` should be 0.

For other tests, look at the examples from the original paper.

If any sample trees need to be included for the tests, they should not be large and they should be added to `tests/data`. Check with @GavinHuttley about patterns to use in this case.

**Comment by rmcar17** [comment]
Hey @GavinHuttley, I'll be happy to begin tackling this.

**Comment by GavinHuttley** [comment]
Add method `TreeNode.lin_rajan_moret()`
Then create issue on needs documentation.
