### ISSUE TITLE
Test suite errors with 0.56.4

### ISSUE THREAD

**Issue by tillea** [cogent3/cogent3#1263]
**Describe the bug**
I tried to build the Debian package of the last tagged release of cogent3 2022.10.31a1 with numba version 0.56.4.  Unfortunately this leads to build time test issues.

**To Reproduce**
There is a [build log in Debian CI](https://salsa.debian.org/med-team/python-cogent/-/jobs/3785100) which shows several errors where I can see lots of references to `numba`.  If you want to see all involved versions you can look at the [raw build log](https://salsa.debian.org/med-team/python-cogent/-/jobs/3785100/raw)

**Expected behavior**
Enable passing the tests with numba 0.56.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: unstable

**Additional context**
Due to the issues with numba there is a problem with cogent3.  We are about to freeze Debian for the next release cycle and thus cogent3 would not be part of the next Debian release if this can't be fixed soon.

Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
This seems to be an error in the Debian build system, trying to compile cogent3 for an unsupported Python version.

cogent3 does not yet support python 3.11 (version limits are defined in our pyproject.toml file and reflected in [the pypi listing](https://pypi.org/project/cogent3/)) because numba does not yet support that version.

**Comment by tillea** [comment]
Am Sun, Jan 15, 2023 at 03:01:04PM -0800 schrieb GavinHuttley:
> This seems to be an error in the Debian build system, trying to compile cogent3 for an unsupported Python version.
>
> cogent3 does not yet support python 3.11 (version limits are defined in our pyproject.toml file and reflected in [the pypi listing](https://pypi.org/project/cogent3/)) because numba does not yet support that version.

The Debian Python team has decided to set Python 3.11 as default and we are working really hard together with numba.  I admit I'm not happy about pushing/forcing 3.11 but we somehow need to deal with this.

Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
I can't do anything until numba is on 3.11. As soon as they've released a 3.11 compatible version, I'll do another release.

**Comment by GavinHuttley** [comment]
Just letting you know that the closest I've been able to find regarding a release date for python 3.11 numba compatible is ~3 weeks away according to [this comment](https://github.com/numba/numba/issues/8304#issuecomment-1404038278) on the numba issue tracker.

**Comment by GavinHuttley** [comment]
Closing this since numba updated
