### ISSUE TITLE
estimate genetic distance from unaligned sequences

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1286]
Given two unaligned k-mer sequences, can we obtain good estimates of the fraction of sites different between them.

We will compare the distance from two unaligned sequences with the proportion of sites that differ between the sequences when aligned.

This is related to #732

**Comment by YapengLang** [comment]
Notebooks relevant to this issue:

1. In this notebook, I compared mash distance (https://pubmed.ncbi.nlm.nih.gov/27323842/) with fractional difference (```distance_matrix()``` in cogent3) by a scatter plot. Data here I used is brca1 (https://github.com/YapengLang/alignment-free-distance/blob/2d7a6db2fc982b05b0833334914a878eab508670/brca1.fasta).
    
    Notebook link: https://github.com/YapengLang/alignment-free-distance/blob/6dab602ddd0af3d647f7bf71a832132c797f916e/progress_report_mash.ipynb

2. Next, I implemented another distance, co-distance (https://pubmed.ncbi.nlm.nih.gov/23335788/). And I plotted error between co-distance and fractional difference vs. length differences, and also a scatter plot for co-distance and fractional difference. Data here is brca1 as above. 

    Notebook link: https://github.com/YapengLang/alignment-free-distance/blob/2d7a6db2fc982b05b0833334914a878eab508670/progress_report_dco.ipynb

3. Then, I explored the relation between ani (our new k-mer based measure) and fractional difference for nucleotide sequences with or without gaps. And I found when k at around 8, no matter the data is gaped or not, the relation appeared to be cubic polynomial. Data is also brca1. 

    Notebook link: https://github.com/YapengLang/alignment-free-distance/blob/2d7a6db2fc982b05b0833334914a878eab508670/progress_report_ani_for_nuc.ipynb

4. Finally, using the brca1 data, I chose an appropriate k (k = 4) and fitted a regression model for amino acid. With the relation function got from brca1 in hand, I used ani to predict fractional difference then converted to Kimura distance which was used to construct the tree. And the whole process applied to other two datasets. For each one, I compared the trees constructed by fractional difference estimates and true fractional difference. Data I used in the order: 

    - brca1 

    - SCA1-cds (https://github.com/YapengLang/alignment-free-distance/blob/b580d54bf03a5ecc05b8bb617b2a857c1fed0530/SCA1-cds.fasta) 

    - transcriptome data of turtle, bird, crocodiles (https://github.com/YapengLang/alignment-free-distance/blob/b580d54bf03a5ecc05b8bb617b2a857c1fed0530/turtle.fasta)

    Notebook link: https://github.com/YapengLang/alignment-free-distance/blob/b580d54bf03a5ecc05b8bb617b2a857c1fed0530/progress_report_ani_for_aa.ipynb

**Comment by KatherineCaley** [comment]
- implement a k-mer-based pairwise distance measure (`k_dist`)
- implement the `distance_matrix()` method on the SequenceCollection class, matching the API from the Alignment version.

something that looks like the following:

``` python
def distance_matrix(self, calc="k_dist", show_progress=False):
        """Returns pairwise distances between unaligned sequences.

        Parameters
        ----------
        calc: str
            a pairwise distance calculator or name of one. default is k_dist.
        """
        calculator = get_distance_calculator(
                calc,
                moltype=self.moltype,
                alignment=self,
                invalid_raises=not drop_invalid,
            )
         calculator.run(show_progress=show_progress)

        result = calculator.get_pairwise_distances()
        return result


```

``` python
def kdist(s1, s2, k):
    """
    Compute a kmer distance that approximates the Average Nucleotide Difference between two sequences.

    Parameters
    ----------
    s1 : str
        The first sequence.
    s2 : str
        The second sequence.
    k : int
        The length of k-mers to use for the calculation.

    Returns
    -------
    float
        The kmer distance between the two sequences.
    """
    # NOTE: we are making sure that s1 is the shorter sequence, as this is important for calculations

    s1, s2 = (s1, s2) if len(s1) < len(s2) else (s2, s1)
    f1 = kfreqs(s1, k)
    f2 = kfreqs(s2, k)

    delta = kmer_count_diff(f1, f2)

    return delta / k / len(s1)
```

**Comment by GavinHuttley** [comment]
I think `k_dist()` should take a `kmer` frequency vector, which can be produced within the `SequenceCollection` method. (Noting that sequences have a`seq.iter_kmers()` method.) The reason is, you want to compute kmers from a sequence only once.
There's also a function for fast computation of kmers and kmer frequencies in `Divergent` which might need to be ported into `cogent3`.

**Comment by KatherineCaley** [comment]
Right. In this case,  we need a way of keeping track of which was the shorter sequence. I realise this can be determined by the frequency of kmers, but I'm assuming we should avoid that calculation too.

**Comment by GavinHuttley** [comment]
fixed in https://github.com/cogent3/cogent3/pull/1431
