### ISSUE TITLE
Discontinue Sequence.translate

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1307]
It’s just delegating to the string method. Better if user just converts sequence to string.

As this is a discontinued function, see [dev guidelines for deprecation](https://github.com/cogent3/c3dev/wiki/Deprecating-Code) of code. Indicate the limiting version (for when the old function will be removed) as 3 months from when you make the change.

**Comment by AoboHill** [comment]
Hi, I am super excited to try to tackle this question!
