### ISSUE TITLE
Publish cogent3 on bioconda

### ISSUE THREAD

**Issue by khiron** [cogent3/cogent3#1311]
- Clone https://github.com/bioconda/bioconda-recipes 
- create a cogent3 branch
- build a YAML file in the recipes folder to install cogent3
- commit, push and create an informative pull request
- once bioconda tests have passed 
- request the installable build and test it

Refer to the following blog for details

https://vijinimallawaarachchi.com/2023/02/11/publishing-python-packages-related-to-bioinformatics-on-bioconda/

**Comment by GavinHuttley** [comment]
I have just contacted the original author of https://github.com/bioconda/bioconda-recipes/pull/37330 to see about modifying his recipe.

**Comment by Vini2** [comment]
The original author is a member of the bioconda organisation and I think he should be fine with us updating the recipe (let's wait till he confirms). We can keep his name under the `recipe-maintainers` section and add names as we put new releases.

**Comment by khiron** [comment]
Updated recipe finally passed all checks and is under BiocondaBot control.

One wrinkle for cogent3 is that Bioconda doesn't appear to be able to condition minimum versions of dependencies upon the version of python.  The cogent3 pyproject.toml can (eg: the minimum version of numba required changes based on which version of python you are using).  The bioconda recipe just sets numba >0.48.0 as the required dependency, which is the minimum required for the oldest version of Python that cogent3 supports.

**Comment by GavinHuttley** [comment]
What's the status of this now?

**Comment by GavinHuttley** [comment]
Done!
