### ISSUE TITLE
Change type argument to biotype in annotations

### ISSUE THREAD

**Issue by khiron** [cogent3/cogent3#1323]
Change the type argument in the annotations DB module from type to biotype

**Comment by GavinHuttley** [comment]
Methods that relate to annotations employ variables named: 
- `type`, e.g. `_Annotation.add_feature()`
- `annotation_type`, e.g. `Alignment.get_annotations_from_any_seq()`
- `annot_types`, e.g. `Alignment.with_masked_annotations()`, `Sequence.annotate_matches_to()`

As some of these methods are over-ridden in different classes, the only safe way to do this deprecation is pick the one method and make the changes to it throughout.

As this is a deprecated function / argument, see [dev guidelines for deprecation](https://github.com/cogent3/c3dev/wiki/Deprecating-Code) of code. Indicate the limiting version (for when the old function / argument will be removed) as 6 months from when you make the change.

**Comment by GavinHuttley** [comment]
fixed ages ago
