### ISSUE TITLE
DEV add a deprecate_arguments decorator

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1324]
There is a pattern to deprecating function / method arguments.

- change the signature to the new argument name(s)
- add a `**kwargs` parameter to the signature
- import the deprecated helper function
- inside the function / method, loop over `**kwargs` for deprecated args, assigning value of deprecated arg  to new parameter and trigger deprecation warning

After the warning period is finished, the signature, import and loop all need to be deleted. This is tedious. It's also quite an ask for new contributors to do all this.

Replace this functionality with a `deprecate_arguments` decorator added to `cogent3.util.misc. warning`. This decorator will allow us to change the method / function signature to its final state and removal

This decorator will:
- accept the same arguments as the utility function, but also a tuple of `old_new` pairs (old name, new name)
- intercept all calls to the wrapped method
-  assigning value of deprecated arg  to new parameter and trigger deprecation warning
- call the wrapped method with the correct signature

**Comment by khiron** [comment]
I have used functools in the past to enable set operator overloading (which otherwise is difficult to do with set operations).

https://github.com/khiron/relation/blob/master/relational_design/wrapfuncs.py

**Comment by khiron** [comment]
VS Code apparently shows any function decorated with a decorator named @deprecated in a strike out font

viz: https://github.com/microsoft/pylance-release/issues/1783

**Comment by khiron** [comment]
Implementation doesn't need to know the old function name as that is implicit in decoration, so it may not be necessary to pass that in a tuple.
