### ISSUE TITLE
ENH: add a data store for reading zip archives

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1328]
We deprecated the original implementation in `cogent3.app.data_store`, but we rely on this in the docs. I think we should support a read only zip data store.

This issue requires:
- reimplementing the deprecated class as a new-style data store
- modifying the `open_data_store()` function to delegate to this class
- updating the docs to using this new class
- adding tests for the new class to `test_data_store_new.py`

**Comment by Nick-Foto** [comment]
Hi Gavin,
I want to do this issue. Please assign it to me.

**Comment by GavinHuttley** [comment]
I think the class should behave like `DirectoryDataStore` in that it copes with a directory that does not have `md5` or `not_completed` sub-directories.
