### ISSUE TITLE
Thinking of the documentation of apps

### ISSUE THREAD

**Issue by YapengLang** [cogent3/cogent3#1378]
- It is unclear in [the model App](https://cogent3.org/doc/app/evo-model-timehet.html#specify-a-distinct-rate-matrix-for-the-great-apes ) doc about how to specify a totally time-heterogeneous model. 
 
  **Suggestion:** it could be better to add more description about the argument ```time_het``` in `get_app("model",
    ...,
    time_het=...
)`.

- For the doc of [Sqlite based](https://cogent3.org/doc/app/dstore.html#sqlitedb-data-stores-for-serialised-data) ```DataStore```, it is not clear to me how to load the ```.sqlitedb``` file. By intuition, I tried to find the relevant apps in ```available_apps()```. But I got lost when I tried ```load_db``` as a loader since its docstring said "Loads serialised cogent3 objects from a db", but it seems we cannot pass ```DataStore``` type directly to this app. Then, I realised that  ```DataStore``` type is a collection. So, I tried to use ```.apply_to()``` but ```load_db``` has no that method.
  
  **Suggestion:** good to give an example of loading ```.sqlitedb``` file under the entry of [Sqlitedb data stores](https://cogent3.org/doc/app/dstore.html#sqlitedb-data-stores-for-serialised-data).

- I'm not clear on what type of argument I should define when I write my own app learnt from [this page](https://cogent3.org/doc/app/user_function.html#turn-your-functions-into-composable-apps). From a couple of examples here, I feel like the Type hint is the type my function will tackle with. My app attempts to take a ```model_result``` and do some calculations. However, I failed to import ```model_result``` from ```cogent3.app.typing```.   

  **Suggestion:** possibly give a table of available types in ```cogent3.app.typing```?

**Comment by GavinHuttley** [comment]
Thanks so much for the feedback @YapengLang ! We will modify the docs, and or the code behaviour.

**Comment by GavinHuttley** [comment]
I have addressed some of this, but more work needs to be done. So I'm changing the milestone of this to Q3 to give us more time to address that.

**Comment by GavinHuttley** [comment]
dealt with in other issues
