### ISSUE TITLE
explore optimisation of compute speed for expm

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#138]
**[Original report](https://bitbucket.org/pycogent3/cogent3-dev/issue/138) by GavinH (Bitbucket: [557058:e40c23e1-e273-4527-a2f8-5de5876e870d](https://bitbucket.org/557058:e40c23e1-e273-4527-a2f8-5de5876e870d), ).**

----------------------------------------

Matrix exponentiation is a central algorithm to computing likelihoods. [Here's useful resource for assisting in addressing this issue.](http://people.duke.edu/~ccc14/sta-663-2017/10B_Numba.html)

There are 2 algorithms of interest implemented in cogent3 (see cogent3.maths.matrix.matrix_exponentiation):

- EigenExponentiator
- PadeExponentiator

These algorithms have what might seem a strange interface -- we provide `Q` as `expm = PadeExponentiator(Q)`, then we get the result of `e^{Qt}` as `expm(t)`. (This interface is there to facilitate caching of intermediate results when possible.)

We need to look at improving the serial compute performance of these. (We do not want threaded / parallel solutions as they lead to CPU collisions).

Addressing this requires development of some benchmarking on the common problems. As the major issue concerns "large" (64 x 64)matrices, we focus on performance of those.

## Step 1 -- develop benchmarking notebook

I suggest we first produce random Q matrices of the required dimension (e.g. see `tests.test_maths.test_measure.gen_q_p()`, without producing `p`) and then benchmark the existing algorithms using the `%time` magic command of jupyter notebooks. So step 1 is to upload a notebook that implements this.

## Step 2 -- assess `scipy` implementations

I understand that `scipy` also has implementations of these algorithms, are they any faster than ours? If so, is that speed due to threading (there is a way to turn threading off...)

## Step 3 -- write and assess a `numba` implementation of matrix power and use that in Pade

This likely requires a custom implementation, outside of `cogent3`, of just the Pade algorithm, that can take advantage of different implementations of matrix power.

When implemented, benchmark and look at different implementations. (For instance, should we turn off the GIL?)

## Step 4 -- write and assess a `cython` implementation

Proceed as for (3).

**Comment by genomematt** [comment]
Is it worth exploring GPU?  This code is from discussion on adding expm to pytorch. https://github.com/Lezcano/expm

**Comment by GavinHuttley** [comment]
That's a great ref, thanks Matt!
