### ISSUE TITLE
cannot provide name as keyword arg to `get_app`

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/cogent3#1403]
the get_app() function raises an error when provided with a descriptive name for the model as a keyword argument. 

e.g., the following code raises a TypeError

```python
hky_as_f81 = get_app("model",
    "HKY85",
    name="HKY85 with κ=1",
    tree="data/brca1_primate.tree",
    param_rules=[dict(par_name="kappa", is_constant=True, value=1)],
)


TypeError: get_app() got multiple values for argument 'name'
``` 

Thanks to Sidney Schmuki for raising this issue!!

**Comment by GavinHuttley** [comment]
This was fixed on [the develop branch](https://github.com/cogent3/cogent3/pull/1303) but has not made it to release yet.
