### ISSUE TITLE
implement SQL set semantics to annotation_db

### ISSUE THREAD

**Issue by khiron** [cogent3/cogent3#1407]
Add "in" argument (tuple) to _matching_conditions in annotations_db

**Comment by GavinHuttley** [comment]
This deals with the SQLlite `IN` operator, see [this SO](https://stackoverflow.com/questions/44394985/how-to-use-the-in-operator-in-sqlite3-with-parameters)

**Comment by GavinHuttley** [comment]
fixed in 2142120
