### ISSUE TITLE
deprecate cogent3.util.table.tolist()

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/cogent3#1466]
(1) copy contents of `tolist` into new method `to_list`, 

(2) decorate old method with:

`@deprecated_callable(version='2023.9', reason='PEP8', new='to_list')`

(3)  replace `tolist` contents with calling the new function 

(4) remove internal calls of `tolist` with `to_list`

**Comment by fredjaya** [comment]
I will work on this!

**Comment by GavinHuttley** [comment]
Awesome! Please read out [contributor guidelines](https://github.com/cogent3/c3dev/wiki). Feel free to post any questions here.

**Comment by fredjaya** [comment]
Hi all, I have made several commits in my forked repo but struggling to push them. This is part of the output when pushing: 
```
nox > Session testdocs-3.10 was successful.
nox > Running session testdocs-3.11
nox > Session testdocs-3.11 skipped: Python interpreter 3.11 not found.
nox > Ran multiple sessions:
nox > * test_slow-3.8: skipped
nox > * test_slow-3.9: failed
nox > * test_slow-3.10: success
nox > * test_slow-3.11: skipped
nox > * test-3.8: skipped
nox > * test-3.9: failed
nox > * test-3.10: success
nox > * test-3.11: skipped
nox > * testmpi-3.8: skipped
nox > * testmpi-3.9: failed
nox > * testmpi-3.10: failed
nox > * testmpi-3.11: skipped
nox > * testdocs-3.8: skipped
nox > * testdocs-3.9: failed
nox > * testdocs-3.10: success
nox > * testdocs-3.11: skipped
error: failed to push some refs to 'github.com:fredjaya/cogent3.git'
```

Is the git error related to the several tests failing? Or an unrelated git issue (which I've tried troubleshooting)?

In case it's useful, this is the output when running `nox -s test-3.10`:
```
========================================= short test summary info ==========================================
SKIPPED [1] test_app/test_app_mpi.py:14: Not using MPI
XFAIL test_align/test_align.py::test_tree_align_pwise_iter - fails on linux due to no effect of iters
XPASS test_app/test_composable.py::test_as_completed_progress[True] passes except when run in full test suit
e
XPASS test_app/test_composable.py::test_as_completed_progress[False] passes except when run in full test sui
te
====== 9461 passed, 1 skipped, 1 deselected, 1 xfailed, 2 xpassed, 566 warnings in 128.66s (0:02:08) =======
nox > Session test-3.10 was successful.
```

**Comment by GavinHuttley** [comment]
Just confirming this output resulted during `git push`?

If so, it looks like there are some very aggressive git pre-commit hooks in place. The `testdocs*` and `testmpi*` don't need to be run for every commit. In fact, I'd only run `test-3.10` or `test-3.11`, whatever python is your standard. So look into editing the precomit hooks of your git config.

**Comment by fredjaya** [comment]
Yes it's the output from `git push`. Will have a look at the pre-commit hooks, thanks!

**Comment by fredjaya** [comment]
Hi again, I want to confirm what the best (correct) way is to replace the internal calls of `tolist`​ with `to_list` throughout the codebase?

I think a search and replace won't work because that will replace the instances of `numpy.ndarray.tolist​`.  

Thanks!

**Comment by KatherineCaley** [comment]
I suggest running the test suite and looking at which calls of `tolist()` triggered a deprecation warning. This will find all of the uses of the method that are tested (which is ideally all of them!)

**Comment by GavinHuttley** [comment]
Extending Kath's suggestions. You can turn the deprecation warnings into errors, which makes it easy to find the exact line
```
$ pytest test_util/ -W "error::DeprecationWarning"
```
as one example

**Comment by GavinHuttley** [comment]
Docs will be harder, because you can't do the same trick. However, just change the rst files talking about tables. Then search for `tolist()`. There should not be any more uses.
