### ISSUE TITLE
Replace favicon on website

### ISSUE THREAD

**Issue by fredjaya** [cogent3/cogent3#1612]
The browser icon for the cogent3 website displays the full logo (below), is it possible to replace it with the square C3 version?

![image](https://github.com/cogent3/cogent3/assets/36436914/166e9ef9-cd1c-4b12-94be-e76536eb201f)

**Comment by GavinHuttley** [comment]
Generate a new .ico file from the attached `svg` and attach to this issue. @khiron can replace the favicon ([stored here](https://github.com/cogent3/cogent3.github.io/tree/develop/doc/_static)).
[c3-square.svg.zip](https://github.com/cogent3/cogent3/files/13036117/c3-square.svg.zip)

**Comment by KatherineCaley** [comment]
TBH I am not the biggest fan of how the square C3 logo looks. My preference would be to just have the "C" for when we want just the icon. Thoughts?

**Comment by GavinHuttley** [comment]
works for me

**Comment by khiron** [comment]
I have a pending PR on the https://github.com/cogent3/cogent3.github.io repository.  I don't have write access to that repository.

**Comment by KatherineCaley** [comment]
svg and png for "C" only icon : 

[c3-icon.zip](https://github.com/cogent3/cogent3/files/13139714/c3-icon.zip)
