### ISSUE TITLE
dotplot doesn't use argument for kmer size, defualt k is buggy

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/cogent3#1619]
`_SequenceCollectionBase.dotplot()`does not pass on the argument for kmer size to the resulting `Dotplot`. This is a simple fix. `Dotplot` has a `k` argument that should receive on the k from `_SequenceCollectionBase.dotplot()` 

As `Dotplot` does not propagate any user-defined k, it will always use `cogent3.align.pycompare._calc_seed_size()` to calculate the k size, and the logic in this function is dubious. 

```python3
def _calc_seed_size(w: int, t: int) -> int:
    """computes k-mer size

    Parameters
    ----------
    w : int
        window size
    t : int
        threshold for minimum number of matches

    Returns
    -------
    int
        returns the larger of (w // k) * k <= t OR w - t + 1
    """
    assert 0 < t <= w, f"threshold={t} > window size={w}"

    # k should be such that (w % k) * k < threshold
    denom = w - t + 1
    return max(min(w // denom, t), denom)
```

`    # k should be such that (w % k) * k < threshold` This is not maintained!! 

In fact, the smaller the proportion of `t/w`, the larger the returned `k` is!!

```python3
  _calc_seed_size(20, 15)
  # 6
```

```python3
  _calc_seed_size(20, 10)
  # 11
```

```python3
  _calc_seed_size(20, 5)
  # 16
```

In the latter cases, `k` is larger than the threshold!

**Comment by KatherineCaley** [comment]
I'm not sure the logic behind the default calculation of `k`, but if k should be such that (w % k) * k < threshold, then it could be calculated in the following way:

```python3 
def _calc_seed_size(w: int, t: int) -> int:

    assert 0 < t <= w, f"threshold={t} > window size={w}"

    # k should be such that (w % k) * k < threshold
    k = 1
    while (w % k) * k < t:
        k += 1

    return k
```

@GavinHuttley let me know if you want me to fix this bug in the above way, or if there are other considerations in calculating a default k.

**Comment by GavinHuttley** [comment]
First, yes the bug should be fixed. Please conceive a test to make sure it's communicated.

I have no idea how I came up with "k should be such that (w % k) * k < threshold"!!

It's a pretty arbitrary calculation regarding `_calc_seed_size()`. Is the following sufficiently robust?

```python
def _calc_seed_size(w: int, t: int) -> int:
    assert 0 < t <= w, f"threshold={t} > window size={w}"
    k = int(math.ceil(math.sqrt(w)))
    if (w // k) * k >= t:
        k = int(math.ceil(math.sqrt(t)))        
    return k
```

**Comment by KatherineCaley** [comment]
Given it's a reasonably arbitrary calculation I think that's fine. 
Note that it will return a substantially smaller default k than the previous implementation which will slow down the dotplot code a lot for larger sequences!

Tests: 
- k cannot be larger than the threshold 
- I think that's it?

**Comment by KatherineCaley** [comment]
Changing the default seed size causes some issues with `find_matched_paths`. Specifically, the code doesn't merge paths that overlap. 

`find_matched_paths` have a value delta, calculated as `delta = (window // k) * (k - 1) + (window - threshold)`, this value of delta is used to determine the left limit for which the function should start extending a seed. I feel like this is where the bug is. 

```python
def test_find_matched_with_rc():
    s = make_seq("CACACCACTGCAGTCGGATAGACC", moltype="dna", name="s1")
    r = s.rc()
    r.name = "rc1"
    k = _calc_seed_size(4, 4)
    expect = _brute_force(s, r, 4, 4)
    sk = SeqKmers(s, k=k, canonical="ACGT")
    # note there's a bug here, it creates a y_intercept at -11
    got = find_matched_paths(seq_kmers=sk, seq1=s, seq2=r, window=4, threshold=4)
    print(got.paths)
    print(expect.paths)

>   assert got.paths == expect.paths
E   Differing items:
{
    4: [
        (segment(start=8, end=14), segment(start=12, end=18)),
        (segment(start=6, end=14), segment(start=10, end=18)),
    ]
} != {4: [(segment(start=6, end=14), segment(start=10, end=18))]}
```

**Comment by GavinHuttley** [comment]
Note in `tests/test_align/test_compare.py `, there's a `_brute_force` function that explicitly considers all paths. That might prove useful for small examples.

**Comment by GavinHuttley** [comment]
@KatherineCaley Note the fix below

First, yes the bug should be fixed. Please conceive a test to make sure it's corrected (i.e. test will fail with current implementation, passes with fix).

## What `_calc_seed_size()` should be doing

Not so tired now, so I recall my intent.


I have no idea how I came up with "k should be such that (w % k) * k < threshold"!!

@KatherineCaley 

Now I'm not so tired, I can explain what should be happening. `_calc_seed_size()` should return the maximum value of `k` that would guarantee the detection of a window of size `w` with exactly `t` matches. Consider `w=20`, `t=18`. Evenly spaced mismatches represent the hardest case. Thus, the value of `k` must satisfy this condition. For the example, the number of mismatches is `d=w-t=2`, and a value of `k=9` is the maximum k can take and satisfy this. Below is a new algorithm that uses this and tries to catch the impractical cases (try changing the return to be only `k` and using `w=20`, `t=14` you get `k=2` which is going to screw up performance. Hence, setting a `min_val` for `k`. 

```python
def _calc_seed_size(w: int, t: int, min_val=5) -> int:
    assert 0 < t <= w, f"threshold={t} > window size={w}"
    d = w - t
    if w == t:
        return w
    elif d > t:
        return t
    k = t // d
    return max(k, min_val)
```

**Comment by GavinHuttley** [comment]
@KatherineCaley 
> The code doesn't seem to merge paths that overlap...

There is a `segment.merge()` method (`cogent3.align.pycompare`) which in turn uses `segment.overlap()`. Try directly creating tests of these methods using your examples.

**Comment by KatherineCaley** [comment]
> There is a `segment.merge()` method (line 52 of `cogent3.align.pycompare`) which in turn uses `segment.overlap()`. Try directly creating tests of these methods using your examples.

Well then the issue is that `find_matched_paths` doesn’t use `segment.overlap()`! If I add a loops which merges the paths (as the brute force approach does), the failing example passes.

**Comment by KatherineCaley** [comment]
> _calc_seed_size() should return the maximum value of k that would guarantee the detection of a window of size w with exactly t matches.

gotcha

**Comment by KatherineCaley** [comment]
```python
def test_find_matched_with_small_seed():
    s1 = make_seq("CACACCACTGCAGTCGGATAGACC", moltype="dna", name="s1")
    s2 = make_seq("GGTCTATCCGACTGCAGTGGTGTG", moltype="dna", name="s2")
    k = 2
    expect = _brute_force(s1, s2, 4, 4)
    sk = SeqKmers(s1, k=k, canonical="ACGT")
    got = find_matched_paths(seq_kmers=sk, seq1=s1, seq2=s2, window=4, threshold=4)
    assert got.paths == expect.paths
```

this test fails when paths are not explicitly merged and passes when there is a merge step

**Comment by GavinHuttley** [comment]
Then you got the fix and the test -- Yay!!
