### ISSUE TITLE
`DistantanceMatrix` should have a method to find max_pair

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/cogent3#1626]
Method should return the two strings that correspond to the maximally divergent pair.

Working on the underlying numpy array is likely the most performant way to implement this. 

sketch:

```py 
def max_pair(self):

  max_index_flat = np.argmax(self)
  max_index_1, max_index_2 = np.unravel_index(max_index_flat, self.shape)
  max_pair = (self.names[max_index_1], self.names[max_index_2])

  return max pair
```

**Comment by GavinHuttley** [comment]
The type hint for this will be
```python
def max_pair(self) -> typing.Tuple[str, str]:
```
I also think that a `min_pair()` method should be implemented.

Examples of these should be added to `doc/cookbook/calc_genetic_distance.rst`. Add a new h2 level headings for `Get names of sequences with max pairwise distance`, same for minimum.

**Comment by KatherineCaley** [comment]
I'll work on this!! 💪
