### ISSUE TITLE
improve error message for invalid sequence file format

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1632]
The so-called "relaxed" phylip format is not handled by the cogent3's phylip parser. But worse is that the error message is not very informative.
For the attached minimal file [locus-0.phy.zip](https://github.com/cogent3/cogent3/files/13421981/locus-0.phy.zip), I get the following error
```python
from cogent3 import load_aligned_seqs

aln = load_aligned_seqs("/Users/gavin/Desktop/Inbox/locus-0.phy", format="phylip", moltype="dna")
```
gives
```
...
   [3840](https://untitled+.vscode-resource.vscode-cdn.net/~/miniconda3/envs/c311/lib/python3.11/site-packages/cogent3/core/alignment.py:3840) seq_lengths = set(len(s) for s in seqs)
   [3841](https://untitled+.vscode-resource.vscode-cdn.net/~/miniconda3/envs/c311/lib/python3.11/site-packages/cogent3/core/alignment.py:3841) if len(seq_lengths) != 1:
-> [3842](https://untitled+.vscode-resource.vscode-cdn.net/~/miniconda3/envs/c311/lib/python3.11/site-packages/cogent3/core/alignment.py:3842)     raise ValueError("not all sequences have same length")

ValueError: not all sequences have same length
```

**Comment by KyleSu12** [comment]
I would like to take this one.

**Comment by GavinHuttley** [comment]
Hmmm, this looks like the error from the version of cogent3 from pypi, not the development version that's in the github repo. This could happen if:
1. you have done a `pip install cogent3` instead of the `flit install ...` command.
2. you have checked out the master branch from github, instead of the develop branch

The way to solve this is establish which git branch you have checked out, I think it's `git branch --show-current`.

The other is to do a long listing of the installed site-packages, i.e. `$ ls -l /home/user/c3/lib/python3.11/site-packages/`. If cogent3 listing looks funny (has an `->` in the report, then you have it correctly installed).

**Comment by KyleSu12** [comment]
Hi, I tried agian, and it turns out that the version i get is the 'develop' one
![image](https://github.com/cogent3/cogent3/assets/141844983/c15791c2-432f-4d0b-85d9-a8d891866877)

**Comment by GavinHuttley** [comment]
can you post the result of the `ls -l` command I showed above.

**Comment by KyleSu12** [comment]
Here I got a very long reult like this:
![image](https://github.com/cogent3/cogent3/assets/141844983/3916fc1e-9d27-4662-bd02-a42eb780cc29)

**Comment by GavinHuttley** [comment]
This is a puzzle!

**Comment by GavinHuttley** [comment]
I figured it out. Recent changes to Cogent3 are why the error is different. You should sync your GitHub fork with the `cogent3/cogent3` parent, then do a git pull within your local Cogent3 copy. The error will change again. It should now look like.
```
File "/Users/gavin/miniconda3/envs/c312/lib/python3.12/site-packages/cogent3/core/alignment.py", line 5532, in _coerce_to_array_aligned_seqs
    return numpy.array(seqs), names
           ^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence
```
This is more useful (I promise!).

**Comment by KyleSu12** [comment]
Oh yeah, I got this, thanks for the guidance!

**Comment by KyleSu12** [comment]
Sorry to interupt agian!
But it seems that the error message now is much more detailed, so I just want to ensure if this issue was actually got fixed...If it was, should I go with another one?
