### ISSUE TITLE
Add support for more tree distance measures

### ISSUE THREAD

**Issue by rmcar17** [cogent3/cogent3#1644]
Currently, the only tree distance measure supported is the Lin-Rajan-Moret distance for unrooted trees (see [A Metric for Phylogenetic Trees Based on Matching](https://ieeexplore.ieee.org/abstract/document/6109232) (Lin et al., 2012)).

There are other commonly used distance measures which would be useful to include inside cogent3. The Robinson-Foulds distance both for rooted and unrooted trees is widely used in the field. For two trees, it is defined as the cardinality of the symmetric difference of the splits in both trees. For rooted trees, clades instead of splits are used.

For Robinson-Foulds, there are a couple of variations in use. Some normalise the distance measure to the interval [0,1], others divide the cardinality of the symmetric difference by two. Dividing by two here turns the measure into a count of the splits/clades not in common. I believe the cardinality of the symmetric difference on its own should be preferred, as it generalises in a more intuitive sense to trees which can contain multifurcating nodes. Users can always normalise the metric themselves if they wish. In any case, due to competing definitions in the literature, the definition used should be made clear in the documentation.

The Robinson-Foulds metric is known to saturate quickly, and it is possible for the measure to achieve its maximum value by moving a single leaf. The Lin-Rajan-Moret distance is a matching distance over the splits of unrooted trees which solves this problem. The analogous matching-based distance over clades of the trees is known as the Matching Cluster distance (see [On a matching distance between rooted phylogenetic trees](https://sciendo.com/article/10.2478/amcs-2013-0050) (Bogdanowicz & Giaro, 2013)) which is essentially a generalised version of the $\beta$ distance to potentially multifurcating trees (see [Metrics on spaces of finite trees](https://www.sciencedirect.com/science/article/pii/0022249673900035) (Boorman & Olivier, 1973)).

@GavinHuttley

**Comment by rmcar17** [comment]
As some additional food for thought, the current tree infrastructure treats all trees as rooted trees under the hood, and checks whether there are more than two children at the root of the tree as for whether to handle it as rooted/unrooted (see for instance `get_sub_tree`, `unrooted` and `lin_rajan_moret`).

This may cause issues when generalising to rooted multifurcating trees. For instance consider:

```python
>>> from cogent3 import make_tree
>>> t = make_tree("(a,(b,c),d);")
>>> t.get_sub_tree(["a","b","c"])
Tree("(a,b,c);")
```
which makes sense if the tree is considered unrooted, though `Tree("(a,(b,c));")` would be expected in the multifurcating rooted case (and is the result of `t._get_sub_tree`).

Unclear what the best solution may be here (a boolean flag could work, but could potentially be messy and prone to error. I see rooted/unrooted trees as different objects, so some abstract tree base class defining common methods with separate rooted/unrooted implementations where necessary could also work (something like UnrootedNode/RootedNode), but would require major changes to the current tree implementation).

Something worth some thought, particularly as the rooted distances generalise to multifurcating rooted trees and as the codebase becomes larger.

**Comment by GavinHuttley** [comment]
@rmcar17 please make the last point a separate issue.
We will need to work through alternate approaches to solving it and the logical complexity. I suspect a mixin class for methods whose algorithm will be unaffected, and your `UnrootedNode` `RootedNode` for the cases that are.

**Comment by GavinHuttley** [comment]
Add new distance functions to `cogent3/phylo/tree_distance.py` and tests to the same place as the Lin-Rajan-Moret case. Try and find edge cases for the tests that are small, re-using existing data when possible.

Are the distance measures all topological only? (That is, edge lengths are ignored.)

`

**Comment by rmcar17** [comment]
> Add new distance functions to `cogent3/phylo/tree_distance.py` and tests to the same place as the Lin-Rajan-Moret case. Try and find edge cases for the tests that are small, re-using existing data when possible.

Will do.

> Are the distance measures all topological only? (That is, edge lengths are ignored.)

Correct, these distance measures only compare the topology of the trees, not considering edge lengths.
