### ISSUE TITLE
Add to the wiki how to test a doc

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1647]
Tow parts to this
1. is the code correct
2. is the restructured text syntax correct

The former can be quickly checked using the helper script `doctest_rsts.py` command. This command needs to be executed from within the doc root directory, i.e. `Cogent3/doc/`.

Addressing 2 is done, within the doc directory using the command
```
$ make html
```
and then open the html docs under `_build/html/index.html` and navigate to the new entry and check it looks OK!

**Comment by fredjaya** [comment]
Noting down here so I don't forget, but it could be useful to have "Documentation workflow" and "practices" pages on the wiki to parallel the Development workflow and practices. Mainly to make it clear that linting and testing of docs and code are different.

**Comment by fredjaya** [comment]
@GavinHuttley should e.g. `nox -s testdocs-3.11` be run as well, or is `doctest_rsts.py` on individual files sufficient?

**Comment by fredjaya** [comment]
Wiki updated. Relevant pages are:
- https://github.com/cogent3/c3dev/wiki/Contributing-documentation
- https://github.com/cogent3/c3dev/wiki/Documentation-types

Let me know if anything else is required!

**Comment by GavinHuttley** [comment]
Edits for the https://github.com/cogent3/c3dev/wiki/Contributing-documentation page:

- [ ] When you embed a snippet of restructured text in Markdown, put `rst` after the opening gates so we get syntax highlighting.
- [ ] Change "After adding or amending code in the .rst files (i.e. jupyter-execute or code-block directives),"  to "After adding or amending code in the .rst files (i.e. `jupyter-execute` or `doctest` directives)," (`code-block` is never executed).
- [ ] last line, because what is built is a static site, they need to open `_build/html/index.html` and navigate to the new content and check it

Regarding https://github.com/cogent3/c3dev/wiki/Documentation-types

- [ ]  CHANGE "Note that the citations should be" to a `> **Note**` line with the content changed to "Only after confirming citations are not already in `cogent3.bib` should they be added to that file."

You can close this when those are done

**Comment by fredjaya** [comment]
Thanks!!

**Comment by fredjaya** [comment]
(Changes made, but I can't close issues)

**Comment by GavinHuttley** [comment]
Thanks @fredjaya !
