### ISSUE TITLE
Add Table.to_pandas() method

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1658]
This is used by plotly express 5.15.

Deprecate the `Table.to_dataframe()` method (check [deprecating code docs](https://github.com/cogent3/c3dev/wiki/Deprecating-code) and replace it with `Table.to_pandas()`. Set the deprecation date as 2024.3 (which corresponds to the Q1 release).

**Comment by fredjaya** [comment]
@GavinHuttley any specific reason for deprecation, or just a rename?

**Comment by GavinHuttley** [comment]
For a public project, we have to avoid breaking the code of users. By adding a deprecation warning, they know how to change their code and by when that change must be done.

**Comment by fredjaya** [comment]
Sorry, to be more specific, any reason for deprecating `Table.to_dataframe()` in place of `Table.to_pandas()`? This is for the `@deprecated_callable(reason=)`

**Comment by GavinHuttley** [comment]
Having Table.to_pandas() means cogent3 tables will be usable by plotly express. So perhaps "to enable usage by plotly"
