### ISSUE TITLE
Add `seq_len` attribute to `SeqView` class

### ISSUE THREAD

**Issue by fredjaya** [cogent3/cogent3#1715]
Currently, `SeqView` can only provide a view of a string, which is assigned to `self.seq`.

We require the ability to have a reference to a string rather than the string itself (i.e. positions in the parent seq). This will be later used for the WIP `SeqDataView` class, which will contain the`seq` data and provide a mechanism to return only a segment of the sequence.

At present, `SeqView` uses `len(self.seq)` in multiple places -- limiting the use of this class to cases where `.seq` is a Python iterable.

We can most easily remove this constraint by adding a `seq_len` argument (and corresponding `self.seq_len` attribute) to the `SeqView` class. 
For the current case of `SeqView.seq` as a string , `seq_len` should default to `None`. If None, assign `len(self.seq)` to `self.seq_len`  in `__init__()`.

Then, replace all uses within `SeqView` code of `len(self.seq)` with `self.seq_len`.

**Note:** because we use slots, we need to add `"seq_len"` to the slots variable too.

**Comment by fredjaya** [comment]
Should `seq_len` be added to the outputs of special methods (i.e. __repr__) and when self is returned?

**Comment by GavinHuttley** [comment]
> Should seq_len be added to the outputs of special methods (i.e. repr)

yes

> and when self is returned?

I don't understand, can you give a specific example?

**Comment by GavinHuttley** [comment]
So in those cases, add the `seq_len=self.seq_len` argument for sure. Since we are planning for the case where subclasses cannot infer that from the value of `self.seq`
