### ISSUE TITLE
amend noxfile to take pytest args from command line

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1718]
The coverage settings should only be automatically applied in GitHub actions. @rmcar17 can you apply the solution you showed me to fixing this.

**Comment by rmcar17** [comment]
Sure thing. Just to clarify - before the recently merged changes, coverage would still be generated when running that nox command. Under the new system, that previous behaviour is ignored and coverage is only generated when the additional arguments are provided to the nox command.

**Comment by GavinHuttley** [comment]
Correct! The additional commands for generating the coverage report need to be added to the `testing_develop.yml`, line 38. So this issue requires patching `noxfile.py` and `testing_develop.yml`
