### ISSUE TITLE
mark poisson_high() function for removal

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1732]
**What should be changed**

`cogent3.maths.stats.poisson_high()`

**Why**

Not used in cogent3, available in scipy.stats?

**How much notice**

6 months notice. This should be represented in the user warning as a specific version. e.g. <current year>.<current month + *x*> where *x* is from the PR date.  

**Guidelines for deprecation**

As this is a function that will be removed, see [dev guidelines for deprecation](https://github.com/cogent3/c3dev/wiki/Deprecating-Code) of code. Indicate the limiting version (for when the old function will be removed) as the number above from when you make the change.

**Comment by Yutong-Shao** [comment]
I would like to do this issue

**Comment by Yutong-Shao** [comment]
I attempted to solve this issue and have submitted a PR. Please have a look, thank you!
