### ISSUE TITLE
mark permutations(), permutations_exact(), ln_permutations() functions for removal

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1736]
**What should be changed**

`cogent3.maths.special.permutations()`, `cogent3.maths.special.permutations_exact()`, `cogent3.maths.special.ln_permutations()`

**Why**

Not used in cogent3, available in scipy.stats?

**How much notice**

6 months notice.

**Guidelines for deprecation**

As this is a function that will be removed, see [dev guidelines for deprecation](https://github.com/cogent3/c3dev/wiki/Deprecating-Code) of code. Indicate the limiting version (for when the old function will be removed) as <current year>.<PR month + *x*> where *x* is defined above.

**Comment by yantonglu** [comment]
I would like to take this one.

**Comment by yantonglu** [comment]
`scipy.special.perm()` may be used as new callable?

**Comment by GavinHuttley** [comment]
You are right, those are autocorrect errors!! Fixing them now.

**Comment by yantonglu** [comment]
1. I found that `scipy.special.perm()` may be used as the new callable. And `scipy.special.perm()` also has exact parameter to determine the precision. Should we retain the `cogent3.maths.species.permutations()` function to continue deciding on precision?

2. When I want to modify a function but not deprecate it, what should I pay attention to and how should I mark or comment?

**Comment by GavinHuttley** [comment]
We are marking those functions as being discontinued, which means we will remove all support by cogent3 developers.

Because the message we add to discontinue the function should be brief, we only specify that there is a replacement. It's up to the user to establish how they map their current usage to the other library.

**Comment by yantonglu** [comment]
> We are marking those functions as being discontinued, which means we will remove all support by cogent3 developers.
> 
> Because the message we add to discontinue the function should be brief, we only specify that there is a replacement. It's up to the user to establish how they map their current usage to the other library.

Got it!

**Comment by yantonglu** [comment]
Here's another problem, if we discontinue `cogent3.maths.species.permutations()`, `test_maths/test_stats/test_special.py::SpecialTests::test_permutations_errors` will failed because the original function raises errors if its parameters are not valid but the new `scipy.special.perm()` does not.

**Comment by GavinHuttley** [comment]
I think just delete `test_permutations_errors`, since we are discontinuing the function.

**Comment by yantonglu** [comment]
> I think just delete `test_permutations_errors`, since we are discontinuing the function.

OK!

**Comment by yantonglu** [comment]
I have fixed them and submitted a PR, please have a look, thanks!

**Comment by GavinHuttley** [comment]
fixed in 1decf70
