### ISSUE TITLE
Add code example snippet to cogent3.app.sample.omit_duplicated

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1752]
The code should be executable by doctesting. See `omit_degenerates()`, `omit_gap_pos()`, `concat()` docstrings for examples. The purpose of these examples is a user gets help on an app and the help displays working code. In other words, the sample code you write should work in an interactive interpreter. It should also not load any data from file, but create sequence collections (in this case) from dictionaries with small sequences.

This app removes redundant sequences from a sequence collection or alignment, i.e. if `seq1` is "ACGG" and `seq2` is also "ACGG", then one of those would be removed from the collection and the dropped sequence name added to the `<collection>.info` object.

See the `test_omit_duplicated_aligned` method in `tests/test_app/test_sample.py` for examples. You should only use a minimal set of data to demonstrate how it works, not the entire data set used for testing.

**Comment by Ruizhe-wang** [comment]
I would like to do this issue
