### ISSUE TITLE
Add code example snippet to cogent3.app.sample.trim_stop_codons

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1754]
The code should be executable by doctesting. See `omit_degenerates()`, `omit_gap_pos()`, `concat()` docstrings for examples. The purpose of these examples is a user gets help on an app and the help displays working code. In other words, the sample code you write should work in an interactive interpreter once the preceding `>>> ` have been removed. It should also not load any data from file, but create sequence collections (in this case) from dictionaries with small sequences.

This app removes trailing stop codons from sequences in a sequence collection or alignment. The output will vary based on whether the input is a sequence collection or an alignment.

For examples, see the `test_trim_stop_codons()` method in `tests/test_app/test_sample.py`. You should only use a minimal data set to demonstrate how it works, not the entire data set used for testing.

**Comment by Lizhaozhe123** [comment]
I would like to do this issue

**Comment by Lizhaozhe123** [comment]
we've already figured out this issue #1767

**Comment by Lizhaozhe123** [comment]
I've already done this issue with #1767
