### ISSUE TITLE
Enh: Allow the construction of "on-the-fly" apps

### ISSUE THREAD

**Issue by khiron** [cogent3/cogent3#1781]
re: https://github.com/cogent3/cogent3/pull/1779#discussion_r1527614150

A function decorated with `@define_app` would likely currently be able to participate in an app composition even if it was not available via `get_app` and it's documentation not available in `app_help`.  We should test that works as expected and document how to do that and provide some examples.

Example: Fred's "bad phylip" file could be fixed up on the fly by defining a function decorated with `@define_app` to take a "bad phylip" and render it on the fly to a good format.

**Comment by GavinHuttley** [comment]
I don't think there's anything to do here. An app's type is created once its module is loaded. What's changing with the plugin approach is that the app is no longer automatically registered and so is not accessible to the `get_app()` and `app_help()` functions. This is OK. If I define an app, I may not want to expose it as an app but instead just use it via direct imports.
