### ISSUE TITLE
annotated information_plot

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#184]
**[Original report](https://bitbucket.org/pycogent3/cogent3-dev/issue/184) by GavinH (Bitbucket: [557058:e40c23e1-e273-4527-a2f8-5de5876e870d](https://bitbucket.org/557058:e40c23e1-e273-4527-a2f8-5de5876e870d), ).**

----------------------------------------

Useful to display annotations when plotting information.

Modify the Alignment.information_plot method (see attached notebook) to support display of annotations. An example of how to construct the AnnotatedDrawable is shown in the Alignment.dotplot method.

This is trickier than it seems because the information plot has 2 y-axes (left and right). So the build fix has to increment yaxes and make sure they're correctly associated.

Chat with Gavin for more details.

**Comment by GavinHuttley** [comment]
Look at the [info plot demo](https://cogent3.readthedocs.io/en/latest/draw/draw-alignment-info-plot.html) and at the [advanced seq handling docs for how to add a feature](https://cogent3.readthedocs.io/en/latest/examples/seq_features.html)
[infoplot.txt](https://github.com/cogent3/cogent3/files/3849628/infoplot.txt)

**Comment by GavinHuttley** [comment]
Add the following into a Jupyter notebook. When executed, `draw` should be an `AnnotatedDrawable` instance that has a bottom track.
```python
from cogent3 import make_seq, make_aligned_seqs, load_aligned_seqs

s1 = make_seq('TGATGTAAGGTAGTT', name='s1', moltype="dna")
s2 = make_seq('--CTGGAAGGGT---', name='s2', moltype="dna")

seqs = make_aligned_seqs(data=[s1, s2], array_align=False, 
                         moltype='dna')
a = seqs.named_seqs["s1"].add_feature("gene", "abc", [(2, 8)])
draw = seqs.information_plot(window=2, include_gap=True)
draw.show(width=500, height=400)
```

**Comment by u6052029** [comment]
Is this the plot outcome that is desired?
![newplot](https://user-images.githubusercontent.com/36777524/69306610-2eddfe80-0c7c-11ea-9384-65a288c16a76.png)

**Comment by GavinHuttley** [comment]
Yes

**Comment by GavinHuttley** [comment]
Additional checks for AnnotatableDrawable, exercising different cases where it's being used. Also added patch that addresses title over-rides
[anno_drawable.txt](https://github.com/cogent3/cogent3/files/3899781/anno_drawable.txt)
[check_tracks.ipynb.zip](https://github.com/cogent3/cogent3/files/3899782/check_tracks.ipynb.zip)
