### ISSUE TITLE
Create new branch with sequence collections backend prototypes

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1860]
call the branch seq-collections-refactor

- [ ] create `src/cogent3/core/new_alignment.py` put the classes and auxiliary functions for sequence data collections / views in there
- [ ] create `tests/test_core/test_new_alignment.py` and put all the tests in there
- [ ] change all your imports so the tests pass

**Comment by fredjaya** [comment]
@GavinHuttley Branch is on my fork here https://github.com/fredjaya/cogent3/tree/seq-collections-refactor. Don't have permissions to add to the main repo though.

**Comment by GavinHuttley** [comment]
thanks @fredjaya!

Can you make a PR from your repo to the new `seq-collections-refactor` branch I created.
