### ISSUE TITLE
The New SeqView foundation

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1865]
Do this in the `develop` branch in current location for `SeqView` class (i.e. `core.sequence`).

An abstract base class foundation for the different types of view. Core attributes for `SliceRecordABC` are.

```
("start", "stop", "step", "_offset", "_seq_len")
```

Needs the following as concrete methods:

- [x] `absolute_position`
- [x] `relative_position`
- [x] ALL methods involved with `__getitem__`
  - [x]  `__getitem__`
  - [x] all related methods

Needs concrete properties for:

- [x] `is_reversed` (just renaming the `reverse` property)
- [x] `parent_start`
- [x] `parent_stop`

All attributes beginning with `_` need a corresponding concrete setter / getter properties without the `_`.
- [x] `_offset` setter and getter
- [x] `_seq_len` setter only at this point

Misc:
- [x] ensure wording in docstring remains consistent with the abstraction

### Updating current SeqView

Inherits from `SliceRecordABC`, deleting methods that are in the ABC but retaining special attributes and methods.

This issue is finished when all current tests pass!

**Comment by KatherineCaley** [comment]
@GavinHuttley 

In `SeqView` we do not provide a setter for `_len_seq`, instead relying on setting the length,`self._seq_len = seq_len or len(self.seq)`, in the constructor. 

Do we want to provide a setter in the ABC, or only allow `_seq_len` to be set in the constructor of inheriting classes?

**Comment by KatherineCaley** [comment]
@GavinHuttley in `SeqView` should I deprecate the `reverse` property (change it to calling `self.is_reversed` and add the deprecation warning, changing other internal usages to `self.is_reversed` ) 

or just remove it and change all internal usages?

**Comment by GavinHuttley** [comment]
> @GavinHuttley in `SeqView` should I deprecate the `reverse` property (it calls`self.is_reversed` and decorate with the deprecation warning, changing other internal usages to `self.is_reversed` )
> 
> or just remove it and change all internal usages?

just remove and replace all internal usage

**Comment by KatherineCaley** [comment]
I've noticed that `cogent3.core.location.Span` uses `reverse` in the same way. Should we change it (for consistency?)

**Comment by KatherineCaley** [comment]
@GavinHuttley  `__getitem__` and related methods (as they are currently used in `SeqView`) require all the arguments to construct another instance. This includes attributes like `seqid`, which we do not require for inheriting classes. 

I started hacking this by having `SeqView.__getitem__` call `super().__getitem__` and provide the `seqid`, and then in the ABC a pass on the `kwargs`. 

```py 
    def __getitem__(self, segment, **kwargs):
        if _is_int(segment):
            start, stop, step = self._get_index(segment)
            return self.__class__(
                self.seq,
                start=start,
                stop=stop,
                step=step,
                offset=self.offset,
                seq_len=self.seq_len,
                **kwargs,
            )

```
However, a better solution might be to not implement `__getitem__` in the ABC. Instead, move the logic into something like a `_get_start_stop_step` function, which then returns those attributes, and the inheriting class is responsible for implementing a `__getitem__` which populates an instance with all required attributes.

**Comment by KatherineCaley** [comment]
@GavinHuttley question above about design choices for the `__getitem__` method in the base class. Since it return a new instance, and this might have different arguments in the inheriting class - what is the best way to approach this?

**Comment by KatherineCaley** [comment]
@GavinHuttley with this approach, we will need to ensure that all subclasses have a positional argument `self.seq`. This makes me think it might be better to be called `data`
