### ISSUE TITLE
modify SeqData

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1866]
- [ ] alphabet must be provided, drop need for the moltype argument
- [ ] add private attribute for `_seq_maker` (it's `Optional[type]`) and setter / getter properties called `seq_maker`
- [ ] modify `__getitem__` so current behaviour (returning `SeqDataView`) occurs if `self._seq_maker is None`
- [ ] `__getitem__` returns self.seq_maker(`SeqDataView`, name) otherwise

**Comment by fredjaya** [comment]
Also
- [ ] add slots to `SeqData` (and `AlignedData`)

**Comment by fredjaya** [comment]
moltype dropped and slots added in 0dbf437

**Comment by fredjaya** [comment]
@GavinHuttley wanting to clarify the intended output and usage of  `seq_maker`.

For example, to return a `cogent3.core.sequence.Sequence`:
```python
data = {"s1": "ACTG", "s2": "ACTGT"}
alpha = get_moltype("dna").alphabets.degen_gapped

# seq_maker can be defined upon construction
seqdata = SeqData(data, alphabet=alpha, seq_maker=Sequence)

# alternatively with the setter
seqdata2 = SeqData(data, alphabet=alpha)
seqdata2.seq_maker = Sequence
```

Should `seqdata["s1"]` be returning the output of `Sequence(seq=data["s1"], name="s1")`?

**Comment by GavinHuttley** [comment]
From your example above, yes. But I would envision assigning the method from the moltype instance, e.g.
```python
data = {"s1": "ACTG", "s2": "ACTGT"}
dna = get_moltype("dna")

# seq_maker can be defined upon construction
seqdata = SeqData(data, alphabet=dna.alphabets.degen_gapped, seq_maker=dna.make_seq)

# alternatively with the setter
seqdata2 = SeqData(data, alphabet=alpha)
seqdata2.seq_maker = dna.make_seq
```

**Comment by GavinHuttley** [comment]
@fredjaya let me qualify, instead of `data["s1"]`, it will be a `SeqDataView(seqid="s1", seq=<the SeqData instance creating the view>)` instance.

**Comment by fredjaya** [comment]
Without `self.seq_maker`, use `__getitem__` to create a `SeqDataView` instance of the correct item.

`SeqDataView` takes:
- `seq = self`
- `seq_len = len(self._data[seqid])`
- `seqid`

With `self.seq_maker`, create `seq_maker(seq=SDV, name=seqid)`

**Comment by fredjaya** [comment]
@GavinHuttley aside from `MolType.make_seq`, are there any other specific methods/types that should be accepted?

**Comment by GavinHuttley** [comment]
The only requirement we should have on the value provided to `seq_maker` is that it's callable. We document that we will invoke the callable with keyword arguments for `seq` and `name`.

**Comment by fredjaya** [comment]
If I understand correctly, `make_seq` (and likely other callables) will return `AttributeError: 'SeqData' object has no attribute 'replace'` if a `SeqDataView` instance is passed as `seq`?  In the example of:
```python
data = {"s1": "ACTG", "s2": "ACTGT"}
dna = get_moltype("dna")
seqdata = SeqData(data, alphabet=dna.alphabets.degen_gapped, seq_maker=dna.make_seq)
```

And the `SeqData` method:
```python
def _make_seq(self, seqid): # called in __getitem__
    seqdataview = self.get_seq_view(seqid=seqid)
    if self._seq_maker is None:
        return seqdataview
    return self._seq_maker(seq=seqdataview, name=seqid)
```

**Comment by GavinHuttley** [comment]
That error is happening because the current implementation of `MolType.make_seq()` does not know about `SeqView` yet. So for now, raise an issue about that and in your tests directly use `<moltype_instance_make_seq>`. That latter just points to the class, which is what you were doing before.
