### ISSUE TITLE
begin new_alignment.SequenceCollection

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1867]
Waiting on #1866

- [x] Create a SequenceCollection class
- [x] SequenceCollection(seq_data=<seq data instance>, moltype=..)
- [x] type hints the constructor
- [x] Assigns seq_data to a `_seq_data` attribute
- [x] Assigns `self._seq_data.seq_maker = self.moltype.make_seq`
- [x] Implements a `seqs` property which returns the `_seq_data`
- [x] Ports relevant tests from `test_alignment.py` into `test_new_alignment.py`, converting them into pytest style (sorry!)
- [x] Implements a `named_seqs` property, which just returns `.seqs` . Deprecate this method and point to just using `.seqs` (give this 12 months).

**Comment by KatherineCaley** [comment]
@GavinHuttley will the new class be inheriting from `_SequenceCollectionBase`?

**Comment by GavinHuttley** [comment]
No. `_SequenceCollectionBase` is an artefact of needing core methods on both `SequenceCollection` (from which `Alignment` directly inherits) and `ArrayAlignment` (which inherits directly from `_SequenceCollectionBase`).

In `new_alignment.py`, define a `SequenceCollection` class without any reference to `alignment.py` classes. All it has to begin with is a constructor and `.seqs` attribute.

**Comment by GavinHuttley** [comment]
closing this as there are now specific issues that are more granular
