### ISSUE TITLE
BUG: updating a db with the same db causes the code to hang

### ISSUE THREAD

**Issue by KatherineCaley** [cogent3/cogent3#1906]
**Describe the bug**
calling `_update_db_from_other_db` where both dbs are the same causes the code to hang

**To Reproduce**
see `tests.test_core.test_ new_alignment.test_sequence_collection_copy_annotations_same_annotations`

**Comment by GavinHuttley** [comment]
There should be a check on identify at the top of `_update_db_from_other_db()`. Because of how the class is implemented this can be done simply as
```python
if other_db == self:
    return
```

**Comment by KatherineCaley** [comment]
fixed in https://github.com/cogent3/cogent3/issues/1906
