### ISSUE TITLE
Sequence and SeqView classes should not be used to replace characters

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1921]
Delete the `_seq_filter()` method from sequence classes in `new_sequence.py`. No longer being used.

Also delete `new_sequence.Sequence.replace()` method.  Users will need to do this explicitly themselves.

There will be side-effects in that some functions (e.g. `moltype._convert_to_rna()` and `_convert_to_dna()`) employ the replace method. We can just produce revised functions that cast incoming data to string and using the replace method on that.

**Comment by KatherineCaley** [comment]
I can work on this

**Comment by KatherineCaley** [comment]
completed in https://github.com/cogent3/cogent3/pull/1935
