### ISSUE TITLE
MolType methods to port

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1932]
- [x] strip_degenerate: use `new_alphabet.convert_alphabet(delete=<all the degenerate characters>)` ?
- [x] disambiguate
- [x] strip_bad: converts to ints and deletes things beyond allowed?
- [x] strip_bad_and_gaps: as above
- [x] count_gaps
- [ ] gap_indices: look at algorithm relationship to `Sequence.parse_out_gaps()`, they should share code
- [ ] gap_vector: where is the method used?
- [ ] gap_maps: do not port, this overlaps with IndelMap
- [x] count_gaps
- [x] count_degenerate
- [x] possibilities: but think of a better name!
- [x] mw
- [ ] can_match: check definition of match, look at test cases, do they seem biologically interesting?
- [ ] can_mismatch: as above
- [x] can_pair
- [x] can_mispair
- [x] must_pair

**Comment by KatherineCaley** [comment]
todo: 
- [ ] strip_degenerate: use `new_alphabet.convert_alphabet(delete=<all the degenerate characters>)` ?
- [ ] disambiguate
- [ ] strip_bad: converts to ints and deletes things beyond allowed?
- [ ] strip_bad_and_gaps: as above
- [ ] count_gaps
- [ ] count_gaps
- [ ] count_degenerate
- [ ] possibilities: but think of a better name!
- [ ] mw
- [ ] can_pair
- [ ] can_mispair
- [ ] must_pair

**Comment by KatherineCaley** [comment]
@GavinHuttley possible other name for `possibilities` is `count_variants`
