### ISSUE TITLE
ENH: implement support for strides in IndelMap

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1967]
The following currently is not supported
```python
import numpy
from cogent3.core.location import IndelMap

im = IndelMap(gap_pos=numpy.array([3, 8]), gap_lengths=numpy.array([2, 1]), parent_length=11)
im[::3]
```
We need to support, this means adjusting the gap positions and the cum_lengths.

**Comment by KatherineCaley** [comment]
@GavinHuttley do we want to support negative strides?

**Comment by GavinHuttley** [comment]
No, users should be explicitly calling `.nucleic_reversed()` on the indelmap. Do we support it Sequence?

**Comment by KatherineCaley** [comment]
we do, but it complicates things...
