### ISSUE TITLE
azure pipeline config for mpi, parallel execution

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#215]
what needs to be done to have a variant test environment that includes mpi?

**Comment by tla256** [comment]
```
thomas@Azure:~$ python
Python 3.5.2 (default, Jul 10 2019, 11:58:48)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing
>>> multiprocessing.cpu_count()
2
```

**Comment by tla256** [comment]
Possible path I'm investigating: Azure Batch

**Comment by tla256** [comment]
Azure Batch is not for testing purposes - it is just a general batch computing service. :(

**Comment by tla256** [comment]
We could duplicate all the machines and run the same script just with MPI installed - that would be the basic approach.
