### ISSUE TITLE
Why "loky"?

### ISSUE THREAD

**Issue by buhtz** [cogent3/cogent3#2187]
Hello,

https://github.com/cogent3/cogent3/blob/a47034827fffdcfd0a3f5187c3a75b1aac44bd8a/pyproject.toml#L18

I try to understand why cognet need this dependency. What is the reason behind it? I couldn't find a document in this repo explaining this design decision.

Thank you in advance,
Christian

**Comment by GavinHuttley** [comment]
Hi,

Sorry it was hard to find the reason for that choice.

In short, loky (which is developed by the team behind joblib) supports parallel execution in Jupyter notebooks which is not easy to do with the standard library multiprocess module.

cheers,

gavin
