### ISSUE TITLE
Add AlignmentI.set_repr_policy method

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#401]
There's a comparable method on the `Table` object which controls how many rows, columns of a table are displayed by `repr()`. We need something similar for sequence alignments. This will require specifying a `_repr_policy` attribute which stores values for `num_seqs` and `num_pos`.

**Comment by GavinHuttley** [comment]
See comments in #174 also.

**Comment by u6052029** [comment]
Where can I test whether the html table for Alignment provides the expected 10 rows and 60 columns?
