### ISSUE TITLE
`progress_display` add time to completion estimate

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#402]
`tqdm` supports this, will it work with our customisation?

**Comment by u6052029** [comment]
Mostly likely not. I believe the estimated time completion uses the size of the collection provided to the tqdm object.
However, with our customisation we do not provide tqdm a collection. Instead, we manually update the progress attribute. We did this to allow progress to be set dynamically in the case it had to be set back.

**Comment by u6052029** [comment]
On further investigation, we should be able to use the estimate. I forgot that we set the tqdm total to 1.0 when we instantiate it. I made a test file is it gave an estimate even though I was manually setting the progress.

We we do not already have the estimate, I need to look at how I formatted the displayed information of the progress display. I may not have added it in.
