### ISSUE TITLE
dot plot does not show alignment if no gaps exist between the sequences

### ISSUE THREAD

**Issue by ChristopherBradley** [cogent3/cogent3#419]
A notebook demonstrating this is attached
[Alignment_without_gaps.ipynb.zip](https://github.com/cogent3/cogent3/files/3908903/Alignment_without_gaps.ipynb.zip)

**Comment by GavinHuttley** [comment]
fixed in c194a78e97cf9a62fdb0c107dc7df5c5e4412e19
