### ISSUE TITLE
add an `annotate_matches_to()` method on Sequence

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#436]
Depends on issue #435

Takes a string or regex, can be IUPAC, and creates an annotation at any matches.
```python
a = seq.annotate_matches_to("AAAYTA", type="domain", name="fred",allow_multiple=False)
a.get_slice()  # returns a sequence matching the pattern
```
If `allow_multiple`, add an integer increment to name as "fred:<number>".

Add this onto the `cogent3.core.sequence.SequenceI` class, and onto the `cogent3.core.alignement.Aligned` class (which just wraps the `Sequence`).

Note, write a docstring for the method, add tests also. See `test_features.FeaturesTest.setUp` for examples.

**Comment by jamesmartini** [comment]
I will volunteer for this issue!
