### ISSUE TITLE
get vector coordinates for all alphabetical letters

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#450]
The attached patch is 6months out-of-date, buyt implements letters for A, C, G, T, U.

Is it possible to get vector coordinates for all English alphabet letters? If so, convert into coordinate sets that can be applied, along with this code.

Just present a notebook demo to start with.

[draw_letter.txt](https://github.com/cogent3/cogent3/files/3953090/draw_letter.txt)

**Comment by u6052029** [comment]
Plotly scatter line:
https://plot.ly/python/reference/#scatter-line

**Comment by u6052029** [comment]
I got SVG letters to render in Plotly with the ability to be transformed, the font family is Inconsolata.

The SVG path used is acquired by the following process:
- Open the Inconsolata OTF in Fontforge.
- Export the letters as SVG files and open them with a text editor.
- Plotly only accepts SVG paths with absolute drawing commands, convert the SVG path found in the SVG file to all absolutes using:
http://lea.verou.me/2019/05/utility-convert-svg-path-to-all-relative-or-all-absolute-commands/
- Paths are stored as an array of SVG segments which is generated from an SVG path string using the following notebook script:
[FormatSVGPath.zip](https://github.com/cogent3/cogent3/files/3981733/FormatSVGPath.zip)


The A is an SVG shape in front of Gavin's original scatter plot T.
![A](https://user-images.githubusercontent.com/36777524/71144995-0e519600-2274-11ea-9615-c5aa078cac6b.png)

In addition to shift and scale;
the letters can be rotated:
![A180](https://user-images.githubusercontent.com/36777524/71145000-10b3f000-2274-11ea-8f1d-176591309636.png)

**Comment by u6052029** [comment]
All the code for these letters are in a Python file called "Letters.py" in the draw folder. Would you like me to push those up even though it is unoptimised?

**Comment by u6052029** [comment]
Rotation still have some issues

letters.py:
[letters.zip](https://github.com/cogent3/cogent3/files/3986327/letters.zip)

**Comment by u6052029** [comment]
Latest versions of letters.py and the SVG path for Plotly converter notebook:

[letters.zip](https://github.com/cogent3/cogent3/files/3986641/letters.zip)
[FormatSVGPath.zip](https://github.com/cogent3/cogent3/files/3986643/FormatSVGPath.zip)

**Comment by u6052029** [comment]
To get a letter into your plot, take the dict returned from the letter class's as_shape method and put it into the array for the plot's shape attribute of layout.

E.g. for the letter C:
cShape = C()
plot.layout["shape"] = [cShape.as_shape()]

**Comment by GavinHuttley** [comment]
The code does not satisfy the style guidelines, pep8 variable / method naming please.

Also, please upload a notebook demonstrating putting multiple letter stacks onto a plot, e.g. 2 stacks, two different letters, the bottom one inverted.

**Comment by u6052029** [comment]
Could you give an example of incorrect styling in letters.py? I believe all my methods and instance variables are lowercase with underscore separation. The only change I could see myself changing is the method "rotate180" to "rotate_180".

**Comment by GavinHuttley** [comment]
variable names in the methods themselves, e.g. `coordIndex` should be `coord_index`, `editedSeg` should be `edited_seg`, etc...

**Comment by u6052029** [comment]
[letter_stack.zip](https://github.com/cogent3/cogent3/files/4038394/letter_stack.zip)
Contains the latest version of letters.py and a notebook example of A and T stacked on top of each other, A rotated 180 degrees.

**Comment by GavinHuttley** [comment]
It looks possible to remove all the class instances and replace them by adding the SVG paths to a module level dict called `_svg_paths`, keyed by their upper case character. Add a `svg_path` argument to the `Letter.__init__`. Then add a module level function called `get_character` that takes the character, the other constructor arguments and returns the letter instance.

In addition:

- write a module docstring explaining the origin of the coordinates (what font, what tools used), etc..
- add the standard boilerplate text regarding contributors, license etc..
- change method name `rotate180` to `invert`
- write some tests!

**Comment by u6052029** [comment]
Currently, the shapes' anchor is at the bottom left corner. Am I right to understand you want A: the anchor to be in the centre of the shape instead? Or  B: the anchor at the bottom of the shape but centred on x?

**Comment by GavinHuttley** [comment]
Here's a notebook demonstrating usage in [MutationMotif](https://github.com/HuttleyLab/MutationMotif/). Fork that repo and modify that code to use the `cogent3.draw` classes.

[demo_draw_logo.ipynb.zip](https://github.com/cogent3/cogent3/files/4043245/demo_draw_logo.ipynb.zip)

**Comment by u6052029** [comment]
Latest version of letters.py with a letter stack example notebook.

[letter_stack_example.zip](https://github.com/cogent3/cogent3/files/4068802/letter_stack_example.zip)

**Comment by u6052029** [comment]
Updated letters.py to support xref and yref
[letters.zip](https://github.com/cogent3/cogent3/files/4075606/letters.zip)
