### ISSUE TITLE
BUG: Aligned.deepcopy not adjusting map correctly

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#487]
attached patch solves one part of the problem, but then the dotplot tests are failing...

[deepcopy.txt](https://github.com/cogent3/cogent3/files/4051877/deepcopy.txt)

**Comment by GavinHuttley** [comment]
The following test exposes the issue explicitly, raising the following `AssertionError: Got {4, 5}, but expected {5}`
```python
    def test_deepcopy2(self):
        """"Aligned.deepcopy handles gapped sequences"""
        seqs = self.Class(data={'Human': 'CAGATTTGGCAGTT-',
                                'Mouse': 'CAGATTCAGCAGGTG'})
        lengths = {len(s.deepcopy(sliced=True)) for s in seqs.seqs}
       self.assertEqual(lengths, {len(seqs)})
```
This issue is arising due to not handling "LostSpans" in the logic of the `Aligned.deepcopy(sliced=True)` method.

**Comment by wjjmjh** [comment]
Thanks Gavin! I spotted the issue as well, I am now working to solve this "LostSpans" issue

**Comment by GavinHuttley** [comment]
I think checking `self.map.spans[0].lost` and `self.map.spans[-1].lost` might help identify when adjustments to parent_length are required.

Modify the sample alignment to have 4 sequences. One with a gap at the end (what I have above), one with a gap at the start, one with a gap in the middle, one with no gap.

**Comment by GavinHuttley** [comment]
@wjjmjh I have a fix for this I'll be pushing in soon, I list you as reviewer so please check it and whether the tests should be supplemented
