### ISSUE TITLE
deprecate cogent3.parse.sequence.format_from_filename

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#683]
Add a deprecation warning to the function, indicate it is replaced by `cogent3.util.misc.get_format_suffixes`.

As this is a deprecated function, see [dev guidelines for deprecation](https://github.com/cogent3/c3dev/wiki/Deprecating-Code) of code. Indicate the limiting version (for when the old function will be removed) as 3 months from when you make the change.

**Comment by pithirat-horvichien** [comment]
Hi, I'd like to solve this issue.
