### ISSUE TITLE
Table.head() failure when number of rows < default

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#699]
```python
from cogent3 import make_table

table = make_table(data=dict(a=['a'], b=['b']))
table.head()
```

raises an index error. I fully expect that `table.tail()` will fail also.

**Comment by wjjmjh** [comment]
Hi Gavin! this works well for me, no index error raised, however, I think this could potentially be a bug:
>>> table = make_table(data=dict(a=[i for i in range(10)], b=[i for i in range(10)]))
>>> table.head(nrows=5)

it turns out the output has got ten rows.

**Comment by wjjmjh** [comment]
oops, sorry Gavin, I spotted the bug, only raised when using a notebook. 

I am on the way of fixing, cheers.
