### ISSUE TITLE
DOC: how to calculate pairwise distances from a sequence collection

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#732]
It's not clear how to do this. The only method available for it is on the Alignment classes...

**Comment by tashachin** [comment]
Hey there! I've never used Cogent3 before, but I thought it'd be helpful to pose some questions (for whoever else may come along).

1. What prerequisites should a documentation contributor know before tackling this task? (i.e. Will one need to research "pairwise distances" or a "sequence collection"?)
2. Where do the Alignment classes live in the repo?
3. Is the calculation method for this issue functional, or is it currently incomplete?
4. Should the documentation exist as a step-by-step tutorial, or would a different format be more useful/concise?

**Comment by GavinHuttley** [comment]
Thanks you @tashachin -- that's an awesome offer and great questions!

As it turns out, in preparing to answer your question I discovered a design issue that needs to be addressed. I'll post that issue and then answer your questions when it's done.

**Comment by GavinHuttley** [comment]
Now clearer how to solve this:

1. implement a k-mer based pairwise distance measure
2. implement the `distance_matrix()` method on the SequenceCollection, match the API from the Alignment version.

**Comment by GavinHuttley** [comment]
fixed in https://github.com/cogent3/cogent3/pull/1431
