### ISSUE TITLE
deprecate interleave_len argument

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#744]
Used in both Alignment and Sequence classes. To methods that use it, add `wrap` argument and use that internally, grabbing `interleave_len` if provided and notifying of argument name change.

Use the `cogent3.warning.deprecated` function to indicate `interleave_len` will be removed in version `2021.6`.

**Comment by Phuong-Le** [comment]
note in case i forget tomorrow: i think it's `cogent3.util.warning.deprecated` rather than `cogent3.warning.deprecated`

**Comment by Phuong-Le** [comment]
note2: Alignment and Sequence are both in src/cogent3/core. I could be wrong but i think you mean AlignmentI and SequenceI? Do Alignment and Sequence have all the methods from AlignmentI and SequenceI or are they completely different?

**Comment by Phuong-Le** [comment]
[rep] note2: I think Sequence is essentially SequenceI with additional features..

**Comment by Phuong-Le** [comment]
[rep] note1: now that I read the deprecation document, the answer is yes..

**Comment by Phuong-Le** [comment]
I pushed the fixed codes to github, waiting for the changes to be checked before i do a pull request

**Comment by Phuong-Le** [comment]
done but could you check `cogent3.format.nexus.nexus_from_alignment` ? the message might not be consistent with the change and i'm not sure if there's a test for it?
