### ISSUE TITLE
demo script for using MPI

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#806]
We need to build a demonstration script for how to use MPI. I'm attaching a zip archive that contains some files for checking parallelisation. Please get that running and validate that it correctly works as is for you on the gadi system at ANU.

Having validated, I want that script converted code to using `cogent3.util.parallel` functions only. Specifically, using the `get_rank()` function instead of directly using `mpi4py` objects directly. (So delete any functions that don't use cogent3.)

Attach revised script to this issue.
[mpi_demo.zip](https://github.com/cogent3/cogent3/files/5491098/mpi_demo.zip)

**Comment by wjjmjh** [comment]
Got the script running in gadi! 
[perf_primes-gah_cogent3.zip](https://github.com/cogent3/cogent3/files/5581540/perf_primes-gah_cogent3.zip)
