### ISSUE TITLE
remove code earmarked deprecated for 2020.11

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#811]
several functions with `deprecated()` call now need to be removed in prep to for release

**Comment by FukurouMakoto** [comment]
I can try taking care of this for you, but just to be sure, do you want them removed completely or replaced with a new function?

**Comment by GavinHuttley** [comment]
@FukurouMakoto Thanks heaps for the offer, but I'm reserving some of these easier issues for summer interns. That will be done within the next day, feel free to put your hand up for other issues after that!
