### ISSUE TITLE
running on armel error: LLVM ERROR: Symbol not found: __sync_fetch_and_add_4

### ISSUE THREAD

**Issue by mr-c** [cogent3/cogent3#818]
From a recent build of 2020.6.30a0 on Debian

https://buildd.debian.org/status/fetch.php?pkg=python-cogent&arch=armel&ver=2020.6.30a0%2Bdfsg-1&stamp=1606735454&raw=0

```
   dh_auto_test -a -O--buildsystem=pybuild
I: pybuild pybuild:284: cp -r /<<PKGBUILDDIR>>/tests/data /<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_cogent3/build
I: pybuild base:232: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_cogent3/build; python3.8 -m unittest discover -v 
LLVM ERROR: Symbol not found: __sync_fetch_and_add_4
E: pybuild pybuild:353: test: plugin distutils failed with: exit code=1: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.8_cogent3/build; python3.8 -m unittest discover -v 
dh_auto_test: error: pybuild --test -i python{version} -p "3.8 3.9" returned exit code 13
```

**Comment by mr-c** [comment]
Running the tests on the mipsel architecture we get a similar error in the same circumstance

```
LLVM ERROR: Symbol not found: __floatdidf
```
https://buildd.debian.org/status/fetch.php?pkg=python-cogent&arch=mipsel&ver=2020.6.30a0%2Bdfsg-1&stamp=1606735937&raw=0

**Comment by GavinHuttley** [comment]
Closing this as from version 2020.12 we now use `numba` and any compilation issues derive from that.

**Comment by mr-c** [comment]
Hello, we still get these errors with cogent3 2020.12.21a; can this issue be re-opened?

https://buildd.debian.org/status/fetch.php?pkg=python-cogent&arch=armel&ver=2020.12.21a%2Bdfsg-3&stamp=1612781156&raw=0

https://buildd.debian.org/status/fetch.php?pkg=python-cogent&arch=mipsel&ver=2020.12.21a%2Bdfsg-3&stamp=1612782448&raw=0

**Comment by GavinHuttley** [comment]
Looking at the error, it's arising during the build of documentation process:
```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.4.3
making output directory... done
WARNING: html_static_path entry '_static' does not exist
[autosummary] generating autosummary for: api/__init__/cogent3.__init__.available_apps.rst, api/__init__/cogent3.__init__.available_codes.rst, api/__init__/cogent3.__init__.available_models.rst, api/__init__/cogent3.__init__.available_moltypes.rst, api/__init__/cogent3.__init__.get_code.rst, api/__init__/cogent3.__init__.get_moltype.rst, api/__init__/cogent3.__init__.load_aligned_seqs.rst, api/__init__/cogent3.__init__.load_table.rst, api/__init__/cogent3.__init__.load_tree.rst, api/__init__/cogent3.__init__.load_unaligned_seqs.rst, ..., examples/scope_model_params_on_trees.rst, examples/seq_features.rst, examples/simple.rst, examples/simulate_alignment.rst, examples/testing_multi_loci.rst, general.rst, index.rst, install.rst, licenses.rst, pycogent.rst
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
generic' is not a recognized processor for this target (ignoring processor)
...
LLVM ERROR: Symbol not found: __floatdidf
make[2]: *** [Makefile:40: html] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/doc'
```
Can you turn off the documentation build? All the docs are available at `cogent3.org`

**Comment by GavinHuttley** [comment]
I should also point out that the main code for building the documentation is [hosted in a separate repo](https://github.com/cogent3/cogent3.github.io).

I retain the actual documentation in this repo for ease of maintenance. The Sphinx Makefile is likewise retained in the doc directory for maintenance, but it's not the production version.

So my recommendation is to skip the documentation build in your packaging, link to cogent3.org instead.

**Comment by mr-c** [comment]
Okay, I tried building without the docs for armel and mipsel, but that segfaulted under qemu. I'll try again on real hardware.

For s390x the build segfaults (on real hardware) while running the tests: https://buildd.debian.org/status/fetch.php?pkg=python-cogent&arch=s390x&ver=2020.12.21a%2Bdfsg-3&stamp=1612781283&raw=0

Likewise for mips64el (also on real hardware) https://buildd.debian.org/status/fetch.php?pkg=python-cogent&arch=mips64el&ver=2020.12.21a%2Bdfsg-3&stamp=1612857835&raw=0

**Comment by mr-c** [comment]
armel and mipsel tests also fail on real hardware 

armel: 
```
I: pybuild pybuild:284: cp -r /home/crusoe/python-cogent-2020.12.21a+dfsg/tests/data /home/crusoe/python-cogent-2020.12.21a+dfsg/.pybuild/cpython3_3.9_cogent3/build
I: pybuild base:232: cd /home/crusoe/python-cogent-2020.12.21a+dfsg/.pybuild/cpython3_3.9_cogent3/build; python3.9 -m pytest -k 'not test_pickleable_member_roundtrip and not
 test_pickleable_roundtrip'                                                                           
============================================================================ test session starts ============================================================================
platform linux -- Python 3.9.1+, pytest-6.0.2, py-1.10.0, pluggy-0.13.0                                                                                                     
rootdir: /home/crusoe/python-cogent-2020.12.21a+dfsg                              
collecting 0 items                                                                                                                                                          E
: pybuild pybuild:353: test: plugin distutils failed with: exit code=1: cd /home/crusoe/python-cogent-2020.12.21a+dfsg/.pybuild/cpython3_3.9_cogent3/build; python3.9 -m pyte
st -k 'not test_pickleable_member_roundtrip and not test_pickleable_roundtrip'                  
dh_auto_test: error: pybuild --test -i python{version} -p 3.9 returned exit code 13        
```

mipsel build with `NUMBA_DEVELOPER_MODE=1` and `-s` added to the `pytest` invocation
```
I: pybuild base:232: cd /home/crusoe/python-cogent-2020.12.21a+dfsg/.pybuild/cpython3_3.9_cogent3/build; python3.9 -m pytest -k 'not test_pickleable_member_roundtrip and not test_pickleable_roundtrip' -s
============================================================================ test session starts ============================================================================
platform linux -- Python 3.9.1+, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/crusoe/python-cogent-2020.12.21a+dfsg
collecting 0 items                                                                                                                                                          'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: Symbol not found: __floatdidf
```

Attached is a mipsel (real hardware) log with `NUMBA_DEBUG=1`

[python-cogent-2020.12.21a+dfsg_mipsel.log](https://github.com/cogent3/cogent3/files/5951713/python-cogent-2020.12.21a%2Bdfsg_mipsel.log)

**Comment by GavinHuttley** [comment]
A couple of remarks:

- both the Debian build logs show it's still building the docs.
- segfault is more likely to come from one of our dependencies (like numba, numpy)
- this is build off the pypi release. Can you assess whether the develop branch of the git repo gives the same issue?


Please note I'm absolutely smashed for time and am unlikely to be free for over a week, so responses will be slow!

**Comment by mr-c** [comment]
>     * both the Debian build logs show it's still building the docs.

Yes, we only skip building the docs on platforms that have problems.

>     * segfault is more likely to come from one of our dependencies (like numba, numpy)

Okay. Assistance in narrowing this down so we can give the right group a good big report will be appreciated

>     * this is build off the pypi release. Can you assess whether the develop branch of the git repo gives the same issue?

Sure, I'll try a snapshot. Would you like a PR to add additional architectures to your CI?

**Comment by GavinHuttley** [comment]
Closing as we can't support platforms for which we don't have access.
