### ISSUE TITLE
jackknife option to provide the original statistic

### ISSUE THREAD

**Issue by Phuong-Le** [cogent3/cogent3#915]
currently the `JackknifeStats` class from `cogent3.maths.stats.jackknife` is calculating the original statistic (`self._sample_statistic` line 60).

the way I defined the `index_gen` is to return the exact same index then `calc_stat` works backward (work out the new statistic for the new subsample using the original data). This means that I can't really use line 60 - I've copied and modified your code so I can use it but I think it'd be really good if there's an option to provide `self._sample_statistic`, especially when this is readily available prior to getting jackknife.

**Comment by GavinHuttley** [comment]
Thanks for the suggestion! Can you post a minimal code example showing how you'd like this to work?

**Comment by Phuong-Le** [comment]
yes, I'll see you in the afternoon.

**Comment by GavinHuttley** [comment]
I think this was just an issue of poor documentation. Addressed in 765976977f08553dc2c72df2041769bb06a26b72
