### ISSUE TITLE
adding two sequences should preserve name

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#957]
adding two sequences with the same name should preserve that name in the result
```python
concat = seq + seq.rc()
```
currently `concat.name` equals `None`

Test should be added to `tests/test_core/test_sequence.py` and specifically as a new method (`test_add()`) at the end of `SequenceTests` (line 943).

Here are the conditions:

- if `seq1.name == seq2.name` then `seq1.name==returned.name`
- else `returned.name is None`

**Comment by bensilke-amd** [comment]
Could I grab this issue?

**Comment by GavinHuttley** [comment]
Hell yes!

**Comment by bensilke-amd** [comment]
This issue was closed by https://github.com/cogent3/cogent3/pull/1003.
