### ISSUE TITLE
License should be a string

### ISSUE THREAD

**Issue by tillea** [cogent3/cogent3#979]
Hi,
with recent setuptools license is required to be a string.  Feel free to incorporate this [patch](https://salsa.debian.org/med-team/python-cogent/-/blob/master/debian/patches/fix-setuptools-FTBFS.patch) we use in Debian.
Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
Thanks @Andreas. I'm puzzled by this since we now use [flit](https://github.com/takluyver/flit). What version of cogent3 are you using?
The [released version](https://pypi.org/project/cogent3/) is 2021.10.12a1.

**Comment by GavinHuttley** [comment]
I should also note that if you need me to make a new release to address the bibtex issue, I'm happy to do it.

**Comment by tillea** [comment]
Am Wed, Nov 03, 2021 at 02:17:08PM -0700 schrieb GavinHuttley:
> Thanks @Andreas. I'm puzzled by this since we now use [flit](https://github.com/takluyver/flit). What version of cogent3 are you using?
> The [released version](https://pypi.org/project/cogent3/) is 2021.10.12a1.

Argh, you are correct.  When I was busy fixing the bug filed in Debian BTS you did another release.  I'll care for this soonish but a release that fixes the bibtex issue would be welcome, thought.  However, I first need to find out how to deal with the replacement of setup.py by pyproject.toml (its the first Python package I see this and I need to find out how to change the packaging toolset).
Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
If it helps, `flit` creates a tarball of the source code which does contain a `setup.py`

**Comment by tillea** [comment]
Am Thu, Nov 04, 2021 at 02:58:21PM -0700 schrieb GavinHuttley:
> If it helps, `flit` creates a tarball of the source code which does contain a `setup.py`
It was no big deal to change the build system and thus I uploaded 2021.10.12a1 yesterday.  Thanks a lot for the hint anyway, Andreas.

**Comment by GavinHuttley** [comment]
This referred to an earlier version.
