### ISSUE TITLE
add support for downloading data files from the web

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#992]
This is related to #934 

In the simplest sense, the following code collects remote data
```python
import urllib.request
import io


url = "https://gavinhuttley.github.io/tib/_downloads/b772b1a069dd1c0925b4e5a7f3ceb4f9/brca1-bats.fasta"
d = urllib.request.urlopen(url)
f = io.TextIOWrapper(d)
```
In the first instance, this requires adding a function to `cogent3.util.io` called `open_url`. What should it return? Should it just be `d`, or `f`? Something else?

The function should fit in with top level load functions, e.g.

```python
from cogent3 import load_aligtned_seqs

aln = load_aligned_seqs(url, moltype="dna")
```
Should work.

We need tests (added to `tests/test_util/test_io.py`) for the case where the remote data is a plain text file of a supported format, and a compressed file of a supported format.

**Comment by Nick-Foto** [comment]
Hi
I would like to solve this issue.
I am going to read contributing guideline and code of conduct before starting.

**Comment by GavinHuttley** [comment]
Awesome! Let me know if you hit any stumbling blocks or need to discuss anything!

**Comment by Nick-Foto** [comment]
Hi
I have written some small code to download file from ftp server. I need some sample addresses to test it. Please provide me some links for ftp, http and https files.
Thank you

**Comment by GavinHuttley** [comment]
Use the cogent3 `tests/data` files.

The base url to all the raw data files (as distinct from GitHub html presentation of those) is `https://raw.githubusercontent.com/cogent3/cogent3/develop/tests/data/`. Here's a couple of examples:
-  the url for  `data/brca1_5.tree` is `https://raw.githubusercontent.com/cogent3/cogent3/develop/tests/data/brca1_5.tree`
-  the url for  `data/sample.tsv` is `https://raw.githubusercontent.com/cogent3/cogent3/develop/tests/data/sample.tsv`

**Comment by Nick-Foto** [comment]
Hi Gavin,

I pushed my changes and created a pull request. Please review and give me comments or merge this.
I removed url as pathlib.Path, because it does not work with "http://" format. It removes one of / characters.
Also I wrote my name as "Nick Shahmaras", because I use this name in work environments. If you don't agree, I can change it.

Thank you
Nabi

**Comment by GavinHuttley** [comment]
Awesome, thanks Nabi!

Happy for you to specify whatever name you like.

Unfortunately, the tests failed because windows uses different line 
endings. You should get a "review" from me via GitHub which outlines how 
to simplify your code and also how to address the test failure.

Cheers,

g
On 28 Jun 2022, at 5:29, Nick-Foto wrote:

> Hi Gavin,
>
> I pushed my changes and created a pull request. Please review and give 
> me comments or merge this.
> I removed url as pathlib.Path, because it does not work with "http://" 
> format. It removes one of / characters.
> Also I wrote my name as "Nick Shahmaras", because I use this name in 
> work environments. If you don't agree, I can change it.
>
> Thank you
> Nabi
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/cogent3/cogent3/issues/992#issuecomment-1167791116
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


----------------------------------
Professor Gavin Huttley,
Convenor, Masters in Quantitative Biology and Bioinformatics,
Research School of Biology,
ANU College of Science,
RN Robertson Building,
46 Sullivans Creek Road,
The Australian National University
Canberra ACT 2600 Australia

+61 2 6125 5308

CRICOS #00120C

----------------------------------
